# Configurations for APIEndpoints. APIServer will
# act on individual methods upon the configurations
# provided.

type: "InterceptorConfig"
validationInterceptor:
  order: 1
  noValidation:
    - "/health.Health/Status"
authenticationInterceptor:
  order: 2
  unauthenticatedEndpoint:
    - "/health.Health/Status"
    - "/auth.v1beta1.Authentication/Login"
    - "/auth.v1beta1.Authentication/Logout"
    - "/auth.v1beta1.Authentication/Token"
    - "/kubernetes.v1beta1.Clusters/StartupScript"
    - "/kubernetes.v1beta1.Clusters/InstanceByIP"
    - "/mailinglist.v1beta1.MailingList/SendEmail"
    - "/mailinglist.v1beta1.MailingList/Subscribe"
    - "/mailinglist.v1beta1.MailingList/Unsubscribe"
    - "/namespace.v1beta1.Teams/Create"
    - "/namespace.v1beta1.Teams/Get"
    - "/namespace.v1beta1.Teams/IsAvailable"
  systemAuthenticatedEndpoint:
    - "/ci.v1beta1.Master/Create"
    - "/ci.v1beta1.Master/Delete"
    - "/backup.v1beta1.Clients/Reconfigure"
    - "/backup.v1beta1.Servers/Create"
    - "/backup.v1beta1.Servers/Delete"
