// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phabnotification.proto

/*
Package v1beta1 is a generated protocol buffer package.

It is generated from these files:
	phabnotification.proto

It has these top-level messages:
	GetResponse
	PhabResult
*/
package v1beta1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/appscodeapis/appscode/api"
import appscode_dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetResponse struct {
	Result []*PhabResult `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetResponse) GetResult() []*PhabResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type PhabResult struct {
	Author    *PhabResult_AuthorInfo `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	BodyText  string                 `protobuf:"bytes,2,opt,name=body_text,json=bodyText" json:"body_text,omitempty"`
	Task      *PhabResult_TaskInfo   `protobuf:"bytes,3,opt,name=task" json:"task,omitempty"`
	UpdatedAt int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	HasViewed int32                  `protobuf:"varint,5,opt,name=has_viewed,json=hasViewed" json:"has_viewed,omitempty"`
}

func (m *PhabResult) Reset()                    { *m = PhabResult{} }
func (m *PhabResult) String() string            { return proto.CompactTextString(m) }
func (*PhabResult) ProtoMessage()               {}
func (*PhabResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PhabResult) GetAuthor() *PhabResult_AuthorInfo {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PhabResult) GetBodyText() string {
	if m != nil {
		return m.BodyText
	}
	return ""
}

func (m *PhabResult) GetTask() *PhabResult_TaskInfo {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *PhabResult) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *PhabResult) GetHasViewed() int32 {
	if m != nil {
		return m.HasViewed
	}
	return 0
}

type PhabResult_AuthorInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Phid string `protobuf:"bytes,2,opt,name=phid" json:"phid,omitempty"`
	Link string `protobuf:"bytes,3,opt,name=link" json:"link,omitempty"`
}

func (m *PhabResult_AuthorInfo) Reset()                    { *m = PhabResult_AuthorInfo{} }
func (m *PhabResult_AuthorInfo) String() string            { return proto.CompactTextString(m) }
func (*PhabResult_AuthorInfo) ProtoMessage()               {}
func (*PhabResult_AuthorInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *PhabResult_AuthorInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PhabResult_AuthorInfo) GetPhid() string {
	if m != nil {
		return m.Phid
	}
	return ""
}

func (m *PhabResult_AuthorInfo) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

type PhabResult_TaskInfo struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Link  string `protobuf:"bytes,2,opt,name=link" json:"link,omitempty"`
}

func (m *PhabResult_TaskInfo) Reset()                    { *m = PhabResult_TaskInfo{} }
func (m *PhabResult_TaskInfo) String() string            { return proto.CompactTextString(m) }
func (*PhabResult_TaskInfo) ProtoMessage()               {}
func (*PhabResult_TaskInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *PhabResult_TaskInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PhabResult_TaskInfo) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func init() {
	proto.RegisterType((*GetResponse)(nil), "appscode.notification.v1beta1.GetResponse")
	proto.RegisterType((*PhabResult)(nil), "appscode.notification.v1beta1.PhabResult")
	proto.RegisterType((*PhabResult_AuthorInfo)(nil), "appscode.notification.v1beta1.PhabResult.AuthorInfo")
	proto.RegisterType((*PhabResult_TaskInfo)(nil), "appscode.notification.v1beta1.PhabResult.TaskInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PhabNotifications service

type PhabNotificationsClient interface {
	// Gets Notifications,
	Get(ctx context.Context, in *appscode_dtypes.VoidRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Update(ctx context.Context, in *appscode_dtypes.VoidRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error)
}

type phabNotificationsClient struct {
	cc *grpc.ClientConn
}

func NewPhabNotificationsClient(cc *grpc.ClientConn) PhabNotificationsClient {
	return &phabNotificationsClient{cc}
}

func (c *phabNotificationsClient) Get(ctx context.Context, in *appscode_dtypes.VoidRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/appscode.notification.v1beta1.PhabNotifications/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phabNotificationsClient) Update(ctx context.Context, in *appscode_dtypes.VoidRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error) {
	out := new(appscode_dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/appscode.notification.v1beta1.PhabNotifications/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PhabNotifications service

type PhabNotificationsServer interface {
	// Gets Notifications,
	Get(context.Context, *appscode_dtypes.VoidRequest) (*GetResponse, error)
	Update(context.Context, *appscode_dtypes.VoidRequest) (*appscode_dtypes.VoidResponse, error)
}

func RegisterPhabNotificationsServer(s *grpc.Server, srv PhabNotificationsServer) {
	s.RegisterService(&_PhabNotifications_serviceDesc, srv)
}

func _PhabNotifications_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(appscode_dtypes.VoidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhabNotificationsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.notification.v1beta1.PhabNotifications/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhabNotificationsServer).Get(ctx, req.(*appscode_dtypes.VoidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhabNotifications_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(appscode_dtypes.VoidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhabNotificationsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.notification.v1beta1.PhabNotifications/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhabNotificationsServer).Update(ctx, req.(*appscode_dtypes.VoidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhabNotifications_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appscode.notification.v1beta1.PhabNotifications",
	HandlerType: (*PhabNotificationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _PhabNotifications_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PhabNotifications_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phabnotification.proto",
}

func init() { proto.RegisterFile("phabnotification.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xd6, 0x3a, 0x3f, 0xc4, 0x93, 0x13, 0x2b, 0x40, 0x96, 0x69, 0xc0, 0xca, 0xc9, 0xad, 0x90,
	0xad, 0x84, 0x9e, 0x2a, 0x71, 0x48, 0x0f, 0x14, 0x24, 0x40, 0xd1, 0xaa, 0xf4, 0xc0, 0x25, 0x5a,
	0xc7, 0xdb, 0x7a, 0x69, 0xea, 0x5d, 0xb2, 0x93, 0xd2, 0x5e, 0x2b, 0x6e, 0x1c, 0x79, 0x09, 0x5e,
	0x80, 0x27, 0xe1, 0x15, 0x78, 0x0d, 0x24, 0xe4, 0xb5, 0x83, 0x93, 0xa2, 0xd2, 0xf4, 0x62, 0x8d,
	0xbf, 0x6f, 0xbf, 0x99, 0x6f, 0x46, 0x33, 0xf0, 0x48, 0x67, 0x3c, 0xc9, 0x15, 0xca, 0x63, 0x39,
	0xe5, 0x28, 0x55, 0x1e, 0xe9, 0xb9, 0x42, 0x45, 0x7b, 0x5c, 0x6b, 0x33, 0x55, 0xa9, 0x88, 0xd6,
	0xc8, 0xf3, 0x41, 0x22, 0x90, 0x0f, 0xfc, 0xad, 0x13, 0xa5, 0x4e, 0x66, 0x22, 0xe6, 0x5a, 0xc6,
	0x3c, 0xcf, 0x15, 0x5a, 0xda, 0x94, 0x62, 0xff, 0xc9, 0x52, 0x7c, 0x03, 0xff, 0x74, 0x8d, 0x4f,
	0xf1, 0x52, 0x0b, 0x13, 0xdb, 0x6f, 0xf9, 0xa0, 0x3f, 0x86, 0xee, 0x81, 0x40, 0x26, 0x8c, 0x56,
	0xb9, 0x11, 0x74, 0x04, 0xed, 0xb9, 0x30, 0x8b, 0x19, 0x7a, 0x24, 0x68, 0x84, 0xdd, 0xe1, 0x76,
	0xf4, 0x5f, 0x77, 0xd1, 0x38, 0xe3, 0x09, 0xb3, 0x02, 0x56, 0x09, 0xfb, 0xbf, 0x1d, 0x80, 0x1a,
	0xa6, 0x6f, 0xa0, 0xcd, 0x17, 0x98, 0xa9, 0xb9, 0x47, 0x02, 0x12, 0x76, 0x87, 0xbb, 0x1b, 0x67,
	0x8c, 0x46, 0x56, 0xf7, 0x3a, 0x3f, 0x56, 0xac, 0xca, 0x41, 0x1f, 0x83, 0x9b, 0xa8, 0xf4, 0x72,
	0x82, 0xe2, 0x02, 0x3d, 0x27, 0x20, 0xa1, 0xcb, 0x3a, 0x05, 0x70, 0x28, 0x2e, 0x90, 0xbe, 0x84,
	0x26, 0x72, 0x73, 0xea, 0x35, 0x6c, 0xa1, 0xe1, 0xe6, 0x85, 0x0e, 0xb9, 0x39, 0xb5, 0x65, 0xac,
	0x9e, 0xf6, 0x00, 0x16, 0x3a, 0xe5, 0x28, 0xd2, 0x09, 0x47, 0xaf, 0x19, 0x90, 0xb0, 0xc1, 0xdc,
	0x0a, 0x19, 0x61, 0x41, 0x67, 0xdc, 0x4c, 0xce, 0xa5, 0xf8, 0x2c, 0x52, 0xaf, 0x15, 0x90, 0xb0,
	0xc5, 0xdc, 0x8c, 0x9b, 0x23, 0x0b, 0xf8, 0xaf, 0x00, 0x6a, 0xe3, 0x94, 0x42, 0x33, 0xe7, 0x67,
	0xc2, 0x36, 0xef, 0x32, 0x1b, 0x17, 0x98, 0xce, 0x64, 0x5a, 0xf9, 0xb7, 0x71, 0x81, 0xcd, 0x64,
	0x5e, 0x7a, 0x77, 0x99, 0x8d, 0xfd, 0x5d, 0xe8, 0x2c, 0x9d, 0xd1, 0x07, 0xd0, 0x42, 0x89, 0xb3,
	0x65, 0xa2, 0xf2, 0xe7, 0xaf, 0xca, 0xa9, 0x55, 0xc3, 0xef, 0x0e, 0xdc, 0x2f, 0x7a, 0x7b, 0xb7,
	0xd2, 0xb4, 0xa1, 0x5f, 0x09, 0x34, 0x0e, 0x04, 0xd2, 0xad, 0x7a, 0x2a, 0xe5, 0x36, 0x44, 0x47,
	0x4a, 0xa6, 0x4c, 0x7c, 0x5a, 0x08, 0x83, 0xfe, 0xce, 0x2d, 0x33, 0x5b, 0x59, 0x95, 0xfe, 0xde,
	0xd5, 0x0f, 0xcf, 0xe9, 0x90, 0xab, 0x9f, 0xbf, 0xbe, 0x39, 0x11, 0x7d, 0x16, 0x4f, 0xd6, 0x56,
	0xed, 0xfa, 0xb2, 0xc7, 0x55, 0x8a, 0xf8, 0xa3, 0x51, 0x39, 0xfd, 0x42, 0xa0, 0xfd, 0xde, 0x0e,
	0xf4, 0x16, 0x43, 0xbd, 0x1b, 0xd8, 0xca, 0xc3, 0x8b, 0x15, 0x0f, 0x83, 0xfe, 0x9d, 0x3c, 0xec,
	0x91, 0x9d, 0xfd, 0xb7, 0xb0, 0x3d, 0x55, 0x67, 0x75, 0x09, 0xae, 0x65, 0xf4, 0xcf, 0x95, 0x56,
	0xa2, 0xfd, 0x87, 0xd7, 0x87, 0x3a, 0x2e, 0x0e, 0x68, 0x4c, 0x3e, 0xdc, 0xab, 0x5e, 0x24, 0x6d,
	0x7b, 0x52, 0xcf, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x73, 0x31, 0xb4, 0xcd, 0xea, 0x03, 0x00,
	0x00,
}
