// Code generated by protoc-gen-grpc-gateway-cors
// source: phabnotification.proto
// DO NOT EDIT!

/*
Package v1beta1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package v1beta1

import "github.com/grpc-ecosystem/grpc-gateway/runtime"

// ExportPhabNotificationsCorsPatterns returns an array of grpc gatway mux patterns for
// PhabNotifications service to enable CORS.
func ExportPhabNotificationsCorsPatterns() []runtime.Pattern {
	return []runtime.Pattern{
		pattern_PhabNotifications_Get_0,
		pattern_PhabNotifications_Update_0,
	}
}
