// Code generated by protoc-gen-go.
// source: operation.proto
// DO NOT EDIT!

/*
Package v1beta1 is a generated protocol buffer package.

It is generated from these files:
	operation.proto

It has these top-level messages:
	Log
	DescribeRequest
	DescribeResponse
	LogDescribeRequest
	LogDescribeResponse
	Auth
	Metadata
	Operation
	NamespaceAdminTaskRequest
*/
package v1beta1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/appscodeapis/appscode/api"
import appscode_dtypes "github.com/appscode/api/dtypes"
import appscode_kubernetes_v1beta1 "github.com/appscode/api/kubernetes/v1beta1"
import appscode_namespace_v1beta1 "github.com/appscode/api/namespace/v1beta1"
import appscode_testlongrunning "github.com/appscode/api/testlongrunning"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Next Id: 18
type OperationType int32

const (
	OperationType_UNKNOWN              OperationType = 0
	OperationType_CLUSTER_CREATE       OperationType = 1
	OperationType_CLUSTER_DELETE       OperationType = 3
	OperationType_CLUSTER_RECONFIGURE  OperationType = 4
	OperationType_NAMESPACE_CREATE     OperationType = 11
	OperationType_NAMESPACE_ADMIN_TASK OperationType = 12
	OperationType_LONG_RUNNING_TEST    OperationType = 13
)

var OperationType_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "CLUSTER_CREATE",
	3:  "CLUSTER_DELETE",
	4:  "CLUSTER_RECONFIGURE",
	11: "NAMESPACE_CREATE",
	12: "NAMESPACE_ADMIN_TASK",
	13: "LONG_RUNNING_TEST",
}
var OperationType_value = map[string]int32{
	"UNKNOWN":              0,
	"CLUSTER_CREATE":       1,
	"CLUSTER_DELETE":       3,
	"CLUSTER_RECONFIGURE":  4,
	"NAMESPACE_CREATE":     11,
	"NAMESPACE_ADMIN_TASK": 12,
	"LONG_RUNNING_TEST":    13,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}
func (OperationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Log struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Log) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Log) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Log) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DescribeRequest struct {
	Phid      string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *DescribeRequest) Reset()                    { *m = DescribeRequest{} }
func (m *DescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*DescribeRequest) ProtoMessage()               {}
func (*DescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DescribeRequest) GetPhid() string {
	if m != nil {
		return m.Phid
	}
	return ""
}

func (m *DescribeRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type DescribeResponse struct {
	Status *appscode_dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Op     *Operation              `protobuf:"bytes,2,opt,name=op" json:"op,omitempty"`
	Logs   []*Log                  `protobuf:"bytes,3,rep,name=logs" json:"logs,omitempty"`
}

func (m *DescribeResponse) Reset()                    { *m = DescribeResponse{} }
func (m *DescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*DescribeResponse) ProtoMessage()               {}
func (*DescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DescribeResponse) GetStatus() *appscode_dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeResponse) GetOp() *Operation {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *DescribeResponse) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type LogDescribeRequest struct {
	Phid  string `protobuf:"bytes,1,opt,name=phid" json:"phid,omitempty"`
	LogId string `protobuf:"bytes,2,opt,name=log_id,json=logId" json:"log_id,omitempty"`
}

func (m *LogDescribeRequest) Reset()                    { *m = LogDescribeRequest{} }
func (m *LogDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*LogDescribeRequest) ProtoMessage()               {}
func (*LogDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LogDescribeRequest) GetPhid() string {
	if m != nil {
		return m.Phid
	}
	return ""
}

func (m *LogDescribeRequest) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}

type LogDescribeResponse struct {
	Status *appscode_dtypes.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Log    *Log                    `protobuf:"bytes,2,opt,name=log" json:"log,omitempty"`
}

func (m *LogDescribeResponse) Reset()                    { *m = LogDescribeResponse{} }
func (m *LogDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*LogDescribeResponse) ProtoMessage()               {}
func (*LogDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LogDescribeResponse) GetStatus() *appscode_dtypes.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LogDescribeResponse) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

type Auth struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Secret    string `protobuf:"bytes,3,opt,name=secret" json:"secret,omitempty"`
	AuthType  string `protobuf:"bytes,4,opt,name=auth_type,json=authType" json:"auth_type,omitempty"`
}

func (m *Auth) Reset()                    { *m = Auth{} }
func (m *Auth) String() string            { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()               {}
func (*Auth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Auth) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Auth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Auth) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Auth) GetAuthType() string {
	if m != nil {
		return m.AuthType
	}
	return ""
}

// Metadata holds other on request or operation specific data
// that could be used inside that operation.
// An welldefined message instead of a map is used
// so that the data fields can be explicitly defined with
// its own data type. Resolves data convertions.
type Metadata struct {
	// Contains PurchasePHID is this is a purchase request.
	PurchasePhids []string `protobuf:"bytes,1,rep,name=purchase_phids,json=purchasePhids" json:"purchase_phids,omitempty"`
	// PHID of the user who requested this operation.
	AuthorPhid string `protobuf:"bytes,2,opt,name=author_phid,json=authorPhid" json:"author_phid,omitempty"`
	AuthorName string `protobuf:"bytes,3,opt,name=author_name,json=authorName" json:"author_name,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Metadata) GetPurchasePhids() []string {
	if m != nil {
		return m.PurchasePhids
	}
	return nil
}

func (m *Metadata) GetAuthorPhid() string {
	if m != nil {
		return m.AuthorPhid
	}
	return ""
}

func (m *Metadata) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

// Next Id: 22
type Operation struct {
	// Types that are valid to be assigned to Request:
	//	*Operation_ClusterCreateRequest
	//	*Operation_ClusterDeleteRequest
	//	*Operation_ClusterReconfigureRequest
	//	*Operation_NamespaceCreateRequest
	//	*Operation_NamespaceAdminTaskRequest
	//	*Operation_LongRunningRequest
	Request  isOperation_Request `protobuf_oneof:"request"`
	Type     OperationType       `protobuf:"varint,14,opt,name=type,enum=appscode.operation.v1beta1.OperationType" json:"type,omitempty"`
	Phid     string              `protobuf:"bytes,15,opt,name=phid" json:"phid,omitempty"`
	Auth     *Auth               `protobuf:"bytes,16,opt,name=auth" json:"auth,omitempty"`
	Metadata *Metadata           `protobuf:"bytes,17,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *Operation) Reset()                    { *m = Operation{} }
func (m *Operation) String() string            { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()               {}
func (*Operation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type isOperation_Request interface {
	isOperation_Request()
}

type Operation_ClusterCreateRequest struct {
	ClusterCreateRequest *appscode_kubernetes_v1beta1.ClusterCreateRequest `protobuf:"bytes,1,opt,name=cluster_create_request,json=clusterCreateRequest,oneof"`
}
type Operation_ClusterDeleteRequest struct {
	ClusterDeleteRequest *appscode_kubernetes_v1beta1.ClusterDeleteRequest `protobuf:"bytes,3,opt,name=cluster_delete_request,json=clusterDeleteRequest,oneof"`
}
type Operation_ClusterReconfigureRequest struct {
	ClusterReconfigureRequest *appscode_kubernetes_v1beta1.ClusterReconfigureRequest `protobuf:"bytes,4,opt,name=cluster_reconfigure_request,json=clusterReconfigureRequest,oneof"`
}
type Operation_NamespaceCreateRequest struct {
	NamespaceCreateRequest *appscode_namespace_v1beta1.CreateRequest `protobuf:"bytes,11,opt,name=namespace_create_request,json=namespaceCreateRequest,oneof"`
}
type Operation_NamespaceAdminTaskRequest struct {
	NamespaceAdminTaskRequest *NamespaceAdminTaskRequest `protobuf:"bytes,12,opt,name=namespace_admin_task_request,json=namespaceAdminTaskRequest,oneof"`
}
type Operation_LongRunningRequest struct {
	LongRunningRequest *appscode_testlongrunning.LongRunningRequest `protobuf:"bytes,22,opt,name=long_running_request,json=longRunningRequest,oneof"`
}

func (*Operation_ClusterCreateRequest) isOperation_Request()      {}
func (*Operation_ClusterDeleteRequest) isOperation_Request()      {}
func (*Operation_ClusterReconfigureRequest) isOperation_Request() {}
func (*Operation_NamespaceCreateRequest) isOperation_Request()    {}
func (*Operation_NamespaceAdminTaskRequest) isOperation_Request() {}
func (*Operation_LongRunningRequest) isOperation_Request()        {}

func (m *Operation) GetRequest() isOperation_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Operation) GetClusterCreateRequest() *appscode_kubernetes_v1beta1.ClusterCreateRequest {
	if x, ok := m.GetRequest().(*Operation_ClusterCreateRequest); ok {
		return x.ClusterCreateRequest
	}
	return nil
}

func (m *Operation) GetClusterDeleteRequest() *appscode_kubernetes_v1beta1.ClusterDeleteRequest {
	if x, ok := m.GetRequest().(*Operation_ClusterDeleteRequest); ok {
		return x.ClusterDeleteRequest
	}
	return nil
}

func (m *Operation) GetClusterReconfigureRequest() *appscode_kubernetes_v1beta1.ClusterReconfigureRequest {
	if x, ok := m.GetRequest().(*Operation_ClusterReconfigureRequest); ok {
		return x.ClusterReconfigureRequest
	}
	return nil
}

func (m *Operation) GetNamespaceCreateRequest() *appscode_namespace_v1beta1.CreateRequest {
	if x, ok := m.GetRequest().(*Operation_NamespaceCreateRequest); ok {
		return x.NamespaceCreateRequest
	}
	return nil
}

func (m *Operation) GetNamespaceAdminTaskRequest() *NamespaceAdminTaskRequest {
	if x, ok := m.GetRequest().(*Operation_NamespaceAdminTaskRequest); ok {
		return x.NamespaceAdminTaskRequest
	}
	return nil
}

func (m *Operation) GetLongRunningRequest() *appscode_testlongrunning.LongRunningRequest {
	if x, ok := m.GetRequest().(*Operation_LongRunningRequest); ok {
		return x.LongRunningRequest
	}
	return nil
}

func (m *Operation) GetType() OperationType {
	if m != nil {
		return m.Type
	}
	return OperationType_UNKNOWN
}

func (m *Operation) GetPhid() string {
	if m != nil {
		return m.Phid
	}
	return ""
}

func (m *Operation) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *Operation) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Operation) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Operation_OneofMarshaler, _Operation_OneofUnmarshaler, _Operation_OneofSizer, []interface{}{
		(*Operation_ClusterCreateRequest)(nil),
		(*Operation_ClusterDeleteRequest)(nil),
		(*Operation_ClusterReconfigureRequest)(nil),
		(*Operation_NamespaceCreateRequest)(nil),
		(*Operation_NamespaceAdminTaskRequest)(nil),
		(*Operation_LongRunningRequest)(nil),
	}
}

func _Operation_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Operation)
	// request
	switch x := m.Request.(type) {
	case *Operation_ClusterCreateRequest:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClusterCreateRequest); err != nil {
			return err
		}
	case *Operation_ClusterDeleteRequest:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClusterDeleteRequest); err != nil {
			return err
		}
	case *Operation_ClusterReconfigureRequest:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClusterReconfigureRequest); err != nil {
			return err
		}
	case *Operation_NamespaceCreateRequest:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NamespaceCreateRequest); err != nil {
			return err
		}
	case *Operation_NamespaceAdminTaskRequest:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NamespaceAdminTaskRequest); err != nil {
			return err
		}
	case *Operation_LongRunningRequest:
		b.EncodeVarint(22<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LongRunningRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Operation.Request has unexpected type %T", x)
	}
	return nil
}

func _Operation_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Operation)
	switch tag {
	case 1: // request.cluster_create_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(appscode_kubernetes_v1beta1.ClusterCreateRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Operation_ClusterCreateRequest{msg}
		return true, err
	case 3: // request.cluster_delete_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(appscode_kubernetes_v1beta1.ClusterDeleteRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Operation_ClusterDeleteRequest{msg}
		return true, err
	case 4: // request.cluster_reconfigure_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(appscode_kubernetes_v1beta1.ClusterReconfigureRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Operation_ClusterReconfigureRequest{msg}
		return true, err
	case 11: // request.namespace_create_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(appscode_namespace_v1beta1.CreateRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Operation_NamespaceCreateRequest{msg}
		return true, err
	case 12: // request.namespace_admin_task_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NamespaceAdminTaskRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Operation_NamespaceAdminTaskRequest{msg}
		return true, err
	case 22: // request.long_running_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(appscode_testlongrunning.LongRunningRequest)
		err := b.DecodeMessage(msg)
		m.Request = &Operation_LongRunningRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Operation_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Operation)
	// request
	switch x := m.Request.(type) {
	case *Operation_ClusterCreateRequest:
		s := proto.Size(x.ClusterCreateRequest)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_ClusterDeleteRequest:
		s := proto.Size(x.ClusterDeleteRequest)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_ClusterReconfigureRequest:
		s := proto.Size(x.ClusterReconfigureRequest)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_NamespaceCreateRequest:
		s := proto.Size(x.NamespaceCreateRequest)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_NamespaceAdminTaskRequest:
		s := proto.Size(x.NamespaceAdminTaskRequest)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Operation_LongRunningRequest:
		s := proto.Size(x.LongRunningRequest)
		n += proto.SizeVarint(22<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NamespaceAdminTaskRequest struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
}

func (m *NamespaceAdminTaskRequest) Reset()                    { *m = NamespaceAdminTaskRequest{} }
func (m *NamespaceAdminTaskRequest) String() string            { return proto.CompactTextString(m) }
func (*NamespaceAdminTaskRequest) ProtoMessage()               {}
func (*NamespaceAdminTaskRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *NamespaceAdminTaskRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func init() {
	proto.RegisterType((*Log)(nil), "appscode.operation.v1beta1.Log")
	proto.RegisterType((*DescribeRequest)(nil), "appscode.operation.v1beta1.DescribeRequest")
	proto.RegisterType((*DescribeResponse)(nil), "appscode.operation.v1beta1.DescribeResponse")
	proto.RegisterType((*LogDescribeRequest)(nil), "appscode.operation.v1beta1.LogDescribeRequest")
	proto.RegisterType((*LogDescribeResponse)(nil), "appscode.operation.v1beta1.LogDescribeResponse")
	proto.RegisterType((*Auth)(nil), "appscode.operation.v1beta1.Auth")
	proto.RegisterType((*Metadata)(nil), "appscode.operation.v1beta1.Metadata")
	proto.RegisterType((*Operation)(nil), "appscode.operation.v1beta1.Operation")
	proto.RegisterType((*NamespaceAdminTaskRequest)(nil), "appscode.operation.v1beta1.NamespaceAdminTaskRequest")
	proto.RegisterEnum("appscode.operation.v1beta1.OperationType", OperationType_name, OperationType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Operations service

type OperationsClient interface {
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	DescribeLog(ctx context.Context, in *LogDescribeRequest, opts ...grpc.CallOption) (*LogDescribeResponse, error)
}

type operationsClient struct {
	cc *grpc.ClientConn
}

func NewOperationsClient(cc *grpc.ClientConn) OperationsClient {
	return &operationsClient{cc}
}

func (c *operationsClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	out := new(DescribeResponse)
	err := grpc.Invoke(ctx, "/appscode.operation.v1beta1.Operations/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsClient) DescribeLog(ctx context.Context, in *LogDescribeRequest, opts ...grpc.CallOption) (*LogDescribeResponse, error) {
	out := new(LogDescribeResponse)
	err := grpc.Invoke(ctx, "/appscode.operation.v1beta1.Operations/DescribeLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Operations service

type OperationsServer interface {
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	DescribeLog(context.Context, *LogDescribeRequest) (*LogDescribeResponse, error)
}

func RegisterOperationsServer(s *grpc.Server, srv OperationsServer) {
	s.RegisterService(&_Operations_serviceDesc, srv)
}

func _Operations_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.operation.v1beta1.Operations/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operations_DescribeLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).DescribeLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.operation.v1beta1.Operations/DescribeLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).DescribeLog(ctx, req.(*LogDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Operations_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appscode.operation.v1beta1.Operations",
	HandlerType: (*OperationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Operations_Describe_Handler,
		},
		{
			MethodName: "DescribeLog",
			Handler:    _Operations_DescribeLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operation.proto",
}

func init() { proto.RegisterFile("operation.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1009 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x51, 0x6e, 0xdb, 0x46,
	0x10, 0x0d, 0x45, 0xd5, 0xb6, 0x46, 0xb1, 0xac, 0x6c, 0x1c, 0x87, 0x71, 0x8c, 0x5a, 0x20, 0x1a,
	0x40, 0x69, 0x53, 0x11, 0x76, 0x9a, 0x16, 0xf9, 0x28, 0x52, 0x59, 0x66, 0x5d, 0x23, 0x32, 0x6d,
	0x50, 0x32, 0x0a, 0xf4, 0x87, 0x5d, 0x53, 0x5b, 0x9a, 0xb5, 0xc4, 0x65, 0xb9, 0xcb, 0x22, 0x46,
	0xd0, 0x8f, 0xe6, 0x0a, 0xbd, 0x42, 0x3f, 0x0b, 0xf4, 0xab, 0x27, 0xe8, 0x11, 0x7a, 0x85, 0x1e,
	0xa1, 0x07, 0x28, 0xb8, 0x24, 0x97, 0x94, 0x1c, 0x29, 0x42, 0x7e, 0x04, 0x71, 0xe6, 0xbd, 0x79,
	0x33, 0xb3, 0xbb, 0xb3, 0x0b, 0x1b, 0x34, 0x24, 0x11, 0xe6, 0x3e, 0x0d, 0x3a, 0x61, 0x44, 0x39,
	0x45, 0xdb, 0x38, 0x0c, 0x99, 0x4b, 0x47, 0xa4, 0x53, 0x78, 0x7e, 0xde, 0xbb, 0x20, 0x1c, 0xef,
	0x6d, 0xef, 0x78, 0x94, 0x7a, 0x63, 0x62, 0xe0, 0xd0, 0x37, 0x70, 0x10, 0x50, 0x2e, 0xdc, 0x2c,
	0x65, 0x6e, 0x7f, 0x98, 0x33, 0xe7, 0xf8, 0x77, 0xa7, 0xfc, 0x23, 0x7e, 0x1d, 0x12, 0x66, 0x88,
	0xdf, 0x0c, 0xf0, 0xe9, 0x14, 0xe0, 0x2a, 0xbe, 0x20, 0x51, 0x40, 0x38, 0x61, 0x46, 0xa6, 0x6f,
	0xb8, 0xe3, 0x98, 0x71, 0x12, 0x65, 0xf0, 0xc7, 0x53, 0xf0, 0x00, 0x4f, 0x08, 0x0b, 0xb1, 0x4b,
	0x24, 0x9a, 0x13, 0x3c, 0xc9, 0xa0, 0x9d, 0x29, 0x28, 0x27, 0x8c, 0x8f, 0x69, 0xe0, 0x45, 0x71,
	0x10, 0xf8, 0x81, 0x67, 0x94, 0xfe, 0xa7, 0x78, 0xfd, 0x04, 0xd4, 0x3e, 0xf5, 0x50, 0x03, 0x2a,
	0xfe, 0x48, 0x53, 0x5a, 0x4a, 0xbb, 0x66, 0x57, 0xfc, 0x11, 0xda, 0x81, 0x1a, 0xf7, 0x27, 0x84,
	0x71, 0x3c, 0x09, 0xb5, 0x4a, 0x4b, 0x69, 0xab, 0x76, 0x61, 0x40, 0x1a, 0xac, 0x4e, 0x08, 0x63,
	0xd8, 0x23, 0x9a, 0x2a, 0x28, 0xf9, 0xa7, 0xde, 0x83, 0x8d, 0x43, 0xc2, 0xdc, 0xc8, 0xbf, 0x20,
	0x36, 0xf9, 0x29, 0x26, 0x8c, 0x23, 0x04, 0xd5, 0xf0, 0x52, 0x06, 0x17, 0xff, 0x17, 0x87, 0xd7,
	0xff, 0x54, 0xa0, 0x59, 0x44, 0x61, 0x21, 0x0d, 0x18, 0x41, 0x06, 0xac, 0x30, 0x8e, 0x79, 0xcc,
	0x44, 0xa0, 0xfa, 0xfe, 0x7d, 0x59, 0x69, 0x27, 0x6d, 0x70, 0x67, 0x20, 0xdc, 0x76, 0x06, 0x43,
	0xcf, 0xa0, 0x42, 0xd3, 0xe0, 0xf5, 0xfd, 0x47, 0x9d, 0xf9, 0x6b, 0xdd, 0x39, 0xcd, 0x2d, 0x76,
	0x85, 0x86, 0xe8, 0x29, 0x54, 0xc7, 0xd4, 0x63, 0x9a, 0xda, 0x52, 0xdb, 0xf5, 0xfd, 0xdd, 0x45,
	0xc4, 0x3e, 0xf5, 0x6c, 0x01, 0xd6, 0x5f, 0x00, 0xea, 0x53, 0x6f, 0x99, 0xca, 0xef, 0xc1, 0xca,
	0x98, 0x7a, 0x8e, 0x3f, 0x12, 0x99, 0xd5, 0xec, 0x0f, 0xc6, 0xd4, 0x3b, 0x1e, 0xe9, 0xd7, 0x70,
	0x77, 0x2a, 0xc0, 0xfb, 0x16, 0xbd, 0x07, 0xea, 0x98, 0x7a, 0x59, 0xd5, 0xef, 0x4c, 0x3e, 0xc1,
	0xea, 0x31, 0x54, 0xbb, 0x31, 0xbf, 0x4c, 0xd6, 0x44, 0xee, 0xac, 0x2c, 0xe5, 0xc2, 0x80, 0xb6,
	0x61, 0x2d, 0x66, 0x24, 0x4a, 0x0c, 0x59, 0xe6, 0xf2, 0x1b, 0x6d, 0xc1, 0x0a, 0x23, 0x6e, 0x44,
	0x78, 0xb6, 0x1b, 0xb2, 0x2f, 0xf4, 0x10, 0x6a, 0x38, 0xe6, 0x97, 0x4e, 0x92, 0xa9, 0x56, 0x4d,
	0x49, 0x89, 0x61, 0x78, 0x1d, 0x12, 0x9d, 0xc1, 0xda, 0x09, 0xe1, 0x78, 0x84, 0x39, 0x46, 0x8f,
	0xa0, 0x11, 0xc6, 0x91, 0x7b, 0x89, 0x19, 0x71, 0x92, 0x2e, 0x25, 0xe5, 0xaa, 0xed, 0x9a, 0xbd,
	0x9e, 0x5b, 0xcf, 0x12, 0x23, 0xda, 0x85, 0x7a, 0x42, 0xa7, 0x91, 0x00, 0x65, 0x69, 0x40, 0x6a,
	0x4a, 0x10, 0x25, 0x80, 0xc8, 0x53, 0x2d, 0x03, 0x2c, 0x3c, 0x21, 0xfa, 0x7f, 0x2b, 0x50, 0x93,
	0xcb, 0x8d, 0x7c, 0xd8, 0xca, 0xce, 0x99, 0xe3, 0x46, 0x04, 0x73, 0xe2, 0x44, 0xe9, 0xca, 0x65,
	0xdd, 0xde, 0x2b, 0xfa, 0x57, 0x1c, 0x51, 0xd9, 0xc0, 0x5e, 0x4a, 0xed, 0x09, 0x66, 0xb6, 0xe4,
	0xdf, 0xdc, 0xb2, 0x37, 0xdd, 0xb7, 0xd8, 0xcb, 0x52, 0x23, 0x32, 0x26, 0x25, 0x29, 0x75, 0x79,
	0xa9, 0x43, 0xc1, 0xbc, 0x29, 0x35, 0x65, 0x47, 0xaf, 0xe0, 0x61, 0x2e, 0x15, 0x11, 0x97, 0x06,
	0x3f, 0xf8, 0x5e, 0x1c, 0x15, 0x7a, 0x55, 0xa1, 0xf7, 0xf9, 0x32, 0x7a, 0x76, 0x41, 0x2f, 0x44,
	0x1f, 0xb8, 0xf3, 0x9c, 0x88, 0x80, 0x26, 0x37, 0xcc, 0x6c, 0x47, 0xeb, 0x42, 0xf6, 0x71, 0x21,
	0x2b, 0x91, 0x85, 0xea, 0x4c, 0x27, 0xb7, 0x24, 0x64, 0xba, 0x97, 0xaf, 0x60, 0xa7, 0x90, 0xc1,
	0xa3, 0x89, 0x1f, 0x38, 0x1c, 0xb3, 0x2b, 0x29, 0x75, 0x5b, 0x48, 0x3d, 0x5b, 0xb4, 0xf9, 0xad,
	0x9c, 0xdf, 0x4d, 0xe8, 0x43, 0xcc, 0xae, 0x4a, 0x05, 0x06, 0xf3, 0x9c, 0xe8, 0x7b, 0xd8, 0x4c,
	0x26, 0xa8, 0x93, 0x8d, 0x50, 0xa9, 0xb8, 0x25, 0x14, 0x9f, 0x14, 0x8a, 0x33, 0x73, 0xb7, 0xd3,
	0xa7, 0x81, 0x67, 0xa7, 0xff, 0x0b, 0x21, 0x34, 0xbe, 0x61, 0x45, 0x5f, 0x42, 0x55, 0x9c, 0x96,
	0x46, 0x4b, 0x69, 0x37, 0xca, 0xed, 0x5a, 0x30, 0xb6, 0x92, 0xe3, 0x64, 0x0b, 0x9a, 0x9c, 0x38,
	0x1b, 0xa5, 0x89, 0xf3, 0x19, 0x54, 0x93, 0x13, 0xa0, 0x35, 0x45, 0x92, 0xad, 0x45, 0x21, 0x93,
	0x39, 0x60, 0x0b, 0x34, 0xfa, 0x0a, 0xd6, 0x26, 0xd9, 0xf1, 0xd4, 0xee, 0x08, 0xe6, 0x47, 0x8b,
	0x98, 0xf9, 0x51, 0xb6, 0x25, 0xeb, 0xa0, 0x06, 0xab, 0x59, 0x7f, 0xf4, 0xe7, 0xf0, 0x60, 0x6e,
	0xc7, 0x17, 0xcf, 0x9d, 0x8f, 0x7f, 0x57, 0x60, 0x7d, 0xaa, 0x52, 0x54, 0x87, 0xd5, 0x73, 0xeb,
	0xa5, 0x75, 0xfa, 0xad, 0xd5, 0xbc, 0x85, 0x10, 0x34, 0x7a, 0xfd, 0xf3, 0xc1, 0xd0, 0xb4, 0x9d,
	0x9e, 0x6d, 0x76, 0x87, 0x66, 0x53, 0x29, 0xdb, 0x0e, 0xcd, 0xbe, 0x39, 0x34, 0x9b, 0x2a, 0xba,
	0x0f, 0x77, 0x73, 0x9b, 0x6d, 0xf6, 0x4e, 0xad, 0xaf, 0x8f, 0x8f, 0xce, 0x6d, 0xb3, 0x59, 0x45,
	0x9b, 0xd0, 0xb4, 0xba, 0x27, 0xe6, 0xe0, 0xac, 0xdb, 0x33, 0xf3, 0x10, 0x75, 0xa4, 0xc1, 0x66,
	0x61, 0xed, 0x1e, 0x9e, 0x1c, 0x5b, 0xce, 0xb0, 0x3b, 0x78, 0xd9, 0xbc, 0x8d, 0xee, 0xc1, 0x9d,
	0xfe, 0xa9, 0x75, 0xe4, 0xd8, 0xe7, 0x96, 0x75, 0x6c, 0x1d, 0x39, 0x43, 0x73, 0x30, 0x6c, 0xae,
	0xef, 0xff, 0xaa, 0x02, 0xc8, 0x34, 0x19, 0xfa, 0x43, 0x81, 0xb5, 0x7c, 0x98, 0xa3, 0x4f, 0x16,
	0x35, 0x6e, 0xe6, 0xce, 0xd8, 0x7e, 0xb2, 0x1c, 0x38, 0xbd, 0x1f, 0x74, 0xf3, 0xcd, 0x5f, 0x5a,
	0x65, 0x4d, 0x79, 0xf3, 0xcf, 0xbf, 0xbf, 0x55, 0x9e, 0xa3, 0x2f, 0x0c, 0x67, 0xea, 0xf6, 0x97,
	0x01, 0xe4, 0x43, 0x41, 0x5a, 0x98, 0xf1, 0x3a, 0xd9, 0x1c, 0xbf, 0x18, 0x3f, 0x32, 0x1a, 0xa0,
	0xbf, 0x15, 0xa8, 0xe7, 0xb1, 0x93, 0xd7, 0x40, 0xe7, 0x1d, 0x17, 0xc7, 0x6c, 0xd2, 0xc6, 0xd2,
	0xf8, 0x2c, 0xef, 0x41, 0x29, 0xef, 0x23, 0x64, 0xbe, 0x47, 0xde, 0xc9, 0xb5, 0x6b, 0xbc, 0x4e,
	0xaf, 0xd2, 0xb4, 0x8a, 0x83, 0x17, 0xa0, 0xbb, 0x74, 0x52, 0xa4, 0x82, 0x43, 0xff, 0x66, 0x3a,
	0x07, 0x0d, 0xb9, 0x4c, 0x67, 0xc9, 0x03, 0xe8, 0x4c, 0xf9, 0x6e, 0x35, 0x73, 0x5d, 0xac, 0x88,
	0x27, 0xd1, 0xd3, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x79, 0x68, 0x8d, 0x4e, 0x2a, 0x0a, 0x00,
	0x00,
}
