// Code generated by protoc-gen-grpc-gateway-cors
// source: longrunning.proto
// DO NOT EDIT!

/*
Package testlongrunning is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package testlongrunning

import "github.com/grpc-ecosystem/grpc-gateway/runtime"

// ExportTestLongRunningCorsPatterns returns an array of grpc gatway mux patterns for
// TestLongRunning service to enable CORS.
func ExportTestLongRunningCorsPatterns() []runtime.Pattern {
	return []runtime.Pattern{
		pattern_TestLongRunning_Run_0,
	}
}
