// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

/*
Package v1beta1 is a generated protocol buffer package.

It is generated from these files:
	cluster.proto
	incident.proto
	loadbalancer.proto
	metadata.proto

It has these top-level messages:
	ClusterSettings
	Cluster
	ClusterDescribeRequest
	ClusterDescribeResponse
	ClusterListRequest
	ClusterListResponse
	InstanceGroup
	ClusterCreateRequest
	ClusterDeleteRequest
	ClusterStartupConfigRequest
	ClusterStartupConfigResponse
	ClusterInstanceByIPRequest
	ClusterInstanceByIPResponse
	ClusterClientConfigRequest
	ClusterClientConfigResponse
	ClusterClientContainerRequest
	ClusterInstance
	ClusterUpdateRequest
	ClusterReconfigureRequest
	Incident
	IncidentListRequest
	IncidentListResponse
	IncidentDescribeRequest
	IncidentDescribeResponse
	IncidentNotifyRequest
	IncidentEventCreateRequest
	ListRequest
	ListResponse
	DescribeRequest
	DescribeResponse
	CreateRequest
	UpdateRequest
	DeleteRequest
	Raw
	LoadBalancer
	Spec
	Status
	LoadBalancerStatus
	LoadBalancerBackend
	LoadBalancerRule
	HTTPLoadBalancerRule
	TCPLoadBalancerRule
	RegionListRequest
	RegionListResponse
	ZoneListRequest
	ZoneListResponse
	BucketListRequest
	BucketListResponse
*/
package v1beta1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/appscodeapis/appscode/api"
import appscode_dtypes "github.com/appscode/api/dtypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClusterSettings struct {
	LogIndexPrefix string `protobuf:"bytes,1,opt,name=logIndexPrefix" json:"logIndexPrefix,omitempty"`
	// Number of secs logs will be stored in ElasticSearch
	LogStorageLifetime int64 `protobuf:"varint,2,opt,name=logStorageLifetime" json:"logStorageLifetime,omitempty"`
	// Number of secs logs will be stored in InfluxDB
	MonitoringStorageLifetime int64 `protobuf:"varint,3,opt,name=monitoringStorageLifetime" json:"monitoringStorageLifetime,omitempty"`
}

func (m *ClusterSettings) Reset()                    { *m = ClusterSettings{} }
func (m *ClusterSettings) String() string            { return proto.CompactTextString(m) }
func (*ClusterSettings) ProtoMessage()               {}
func (*ClusterSettings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClusterSettings) GetLogIndexPrefix() string {
	if m != nil {
		return m.LogIndexPrefix
	}
	return ""
}

func (m *ClusterSettings) GetLogStorageLifetime() int64 {
	if m != nil {
		return m.LogStorageLifetime
	}
	return 0
}

func (m *ClusterSettings) GetMonitoringStorageLifetime() int64 {
	if m != nil {
		return m.MonitoringStorageLifetime
	}
	return 0
}

type Cluster struct {
	Uid                  string            `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Provider             string            `protobuf:"bytes,3,opt,name=provider" json:"provider,omitempty"`
	Os                   string            `protobuf:"bytes,4,opt,name=os" json:"os,omitempty"`
	Region               string            `protobuf:"bytes,5,opt,name=region" json:"region,omitempty"`
	Zone                 string            `protobuf:"bytes,6,opt,name=zone" json:"zone,omitempty"`
	CreatedAt            int64             `protobuf:"varint,7,opt,name=createdAt" json:"createdAt,omitempty"`
	Links                map[string]string `protobuf:"bytes,8,rep,name=links" json:"links,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DoNotDelete          bool              `protobuf:"varint,9,opt,name=doNotDelete" json:"doNotDelete,omitempty"`
	Status               string            `protobuf:"bytes,10,opt,name=status" json:"status,omitempty"`
	StatusCause          string            `protobuf:"bytes,11,opt,name=statusCause" json:"statusCause,omitempty"`
	GceProject           string            `protobuf:"bytes,12,opt,name=gceProject" json:"gceProject,omitempty"`
	KubeletVersion       string            `protobuf:"bytes,13,opt,name=kubeletVersion" json:"kubeletVersion,omitempty"`
	SaltbaseVersion      string            `protobuf:"bytes,14,opt,name=saltbaseVersion" json:"saltbaseVersion,omitempty"`
	KubeStarterVersion   string            `protobuf:"bytes,15,opt,name=kubeStarterVersion" json:"kubeStarterVersion,omitempty"`
	NodeCount            int32             `protobuf:"varint,16,opt,name=nodeCount" json:"nodeCount,omitempty"`
	ApiServerUrl         string            `protobuf:"bytes,17,opt,name=apiServerUrl" json:"apiServerUrl,omitempty"`
	KubeUser             string            `protobuf:"bytes,18,opt,name=kubeUser" json:"kubeUser,omitempty"`
	KubePassword         string            `protobuf:"bytes,19,opt,name=kubePassword" json:"kubePassword,omitempty"`
	CaCert               string            `protobuf:"bytes,20,opt,name=caCert" json:"caCert,omitempty"`
	KubeBearerToken      string            `protobuf:"bytes,21,opt,name=kubeBearerToken" json:"kubeBearerToken,omitempty"`
	Settings             *ClusterSettings  `protobuf:"bytes,22,opt,name=settings" json:"settings,omitempty"`
	InstanceRootPassword string            `protobuf:"bytes,23,opt,name=instanceRootPassword" json:"instanceRootPassword,omitempty"`
	Version              string            `protobuf:"bytes,24,opt,name=version" json:"version,omitempty"`
	Sku                  string            `protobuf:"bytes,25,opt,name=sku" json:"sku,omitempty"`
	CreatedBy            string            `protobuf:"bytes,26,opt,name=createdBy" json:"createdBy,omitempty"`
	DefaultAccessLevel   string            `protobuf:"bytes,27,opt,name=defaultAccessLevel" json:"defaultAccessLevel,omitempty"`
}

func (m *Cluster) Reset()                    { *m = Cluster{} }
func (m *Cluster) String() string            { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()               {}
func (*Cluster) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Cluster) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Cluster) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *Cluster) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Cluster) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *Cluster) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Cluster) GetLinks() map[string]string {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Cluster) GetDoNotDelete() bool {
	if m != nil {
		return m.DoNotDelete
	}
	return false
}

func (m *Cluster) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Cluster) GetStatusCause() string {
	if m != nil {
		return m.StatusCause
	}
	return ""
}

func (m *Cluster) GetGceProject() string {
	if m != nil {
		return m.GceProject
	}
	return ""
}

func (m *Cluster) GetKubeletVersion() string {
	if m != nil {
		return m.KubeletVersion
	}
	return ""
}

func (m *Cluster) GetSaltbaseVersion() string {
	if m != nil {
		return m.SaltbaseVersion
	}
	return ""
}

func (m *Cluster) GetKubeStarterVersion() string {
	if m != nil {
		return m.KubeStarterVersion
	}
	return ""
}

func (m *Cluster) GetNodeCount() int32 {
	if m != nil {
		return m.NodeCount
	}
	return 0
}

func (m *Cluster) GetApiServerUrl() string {
	if m != nil {
		return m.ApiServerUrl
	}
	return ""
}

func (m *Cluster) GetKubeUser() string {
	if m != nil {
		return m.KubeUser
	}
	return ""
}

func (m *Cluster) GetKubePassword() string {
	if m != nil {
		return m.KubePassword
	}
	return ""
}

func (m *Cluster) GetCaCert() string {
	if m != nil {
		return m.CaCert
	}
	return ""
}

func (m *Cluster) GetKubeBearerToken() string {
	if m != nil {
		return m.KubeBearerToken
	}
	return ""
}

func (m *Cluster) GetSettings() *ClusterSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *Cluster) GetInstanceRootPassword() string {
	if m != nil {
		return m.InstanceRootPassword
	}
	return ""
}

func (m *Cluster) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Cluster) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Cluster) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Cluster) GetDefaultAccessLevel() string {
	if m != nil {
		return m.DefaultAccessLevel
	}
	return ""
}

type ClusterDescribeRequest struct {
	Uid string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *ClusterDescribeRequest) Reset()                    { *m = ClusterDescribeRequest{} }
func (m *ClusterDescribeRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterDescribeRequest) ProtoMessage()               {}
func (*ClusterDescribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ClusterDescribeRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type ClusterDescribeResponse struct {
	Cluster       *Cluster                             `protobuf:"bytes,1,opt,name=cluster" json:"cluster,omitempty"`
	Spec          *ClusterDescribeResponse_ClusterSpec `protobuf:"bytes,2,opt,name=spec" json:"spec,omitempty"`
	OperationPhid string                               `protobuf:"bytes,3,opt,name=operationPhid" json:"operationPhid,omitempty"`
}

func (m *ClusterDescribeResponse) Reset()                    { *m = ClusterDescribeResponse{} }
func (m *ClusterDescribeResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterDescribeResponse) ProtoMessage()               {}
func (*ClusterDescribeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ClusterDescribeResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *ClusterDescribeResponse) GetSpec() *ClusterDescribeResponse_ClusterSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ClusterDescribeResponse) GetOperationPhid() string {
	if m != nil {
		return m.OperationPhid
	}
	return ""
}

type ClusterDescribeResponse_ClusterSpec struct {
	ContainerCount int32 `protobuf:"varint,1,opt,name=containerCount" json:"containerCount,omitempty"`
	PodCount       int32 `protobuf:"varint,2,opt,name=podCount" json:"podCount,omitempty"`
	ServiceCount   int32 `protobuf:"varint,3,opt,name=serviceCount" json:"serviceCount,omitempty"`
	RcCount        int32 `protobuf:"varint,4,opt,name=rcCount" json:"rcCount,omitempty"`
	TotalCpu       int64 `protobuf:"varint,5,opt,name=totalCpu" json:"totalCpu,omitempty"`
	TotalMemory    int64 `protobuf:"varint,6,opt,name=totalMemory" json:"totalMemory,omitempty"`
}

func (m *ClusterDescribeResponse_ClusterSpec) Reset()         { *m = ClusterDescribeResponse_ClusterSpec{} }
func (m *ClusterDescribeResponse_ClusterSpec) String() string { return proto.CompactTextString(m) }
func (*ClusterDescribeResponse_ClusterSpec) ProtoMessage()    {}
func (*ClusterDescribeResponse_ClusterSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

func (m *ClusterDescribeResponse_ClusterSpec) GetContainerCount() int32 {
	if m != nil {
		return m.ContainerCount
	}
	return 0
}

func (m *ClusterDescribeResponse_ClusterSpec) GetPodCount() int32 {
	if m != nil {
		return m.PodCount
	}
	return 0
}

func (m *ClusterDescribeResponse_ClusterSpec) GetServiceCount() int32 {
	if m != nil {
		return m.ServiceCount
	}
	return 0
}

func (m *ClusterDescribeResponse_ClusterSpec) GetRcCount() int32 {
	if m != nil {
		return m.RcCount
	}
	return 0
}

func (m *ClusterDescribeResponse_ClusterSpec) GetTotalCpu() int64 {
	if m != nil {
		return m.TotalCpu
	}
	return 0
}

func (m *ClusterDescribeResponse_ClusterSpec) GetTotalMemory() int64 {
	if m != nil {
		return m.TotalMemory
	}
	return 0
}

type ClusterListRequest struct {
	Status []string `protobuf:"bytes,1,rep,name=status" json:"status,omitempty"`
}

func (m *ClusterListRequest) Reset()                    { *m = ClusterListRequest{} }
func (m *ClusterListRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterListRequest) ProtoMessage()               {}
func (*ClusterListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ClusterListRequest) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

type ClusterListResponse struct {
	Clusters []*Cluster `protobuf:"bytes,1,rep,name=clusters" json:"clusters,omitempty"`
}

func (m *ClusterListResponse) Reset()                    { *m = ClusterListResponse{} }
func (m *ClusterListResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterListResponse) ProtoMessage()               {}
func (*ClusterListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ClusterListResponse) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

type InstanceGroup struct {
	Sku              string `protobuf:"bytes,1,opt,name=sku" json:"sku,omitempty"`
	Count            int64  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	UseSpotInstances bool   `protobuf:"varint,3,opt,name=useSpotInstances" json:"useSpotInstances,omitempty"`
}

func (m *InstanceGroup) Reset()                    { *m = InstanceGroup{} }
func (m *InstanceGroup) String() string            { return proto.CompactTextString(m) }
func (*InstanceGroup) ProtoMessage()               {}
func (*InstanceGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InstanceGroup) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *InstanceGroup) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *InstanceGroup) GetUseSpotInstances() bool {
	if m != nil {
		return m.UseSpotInstances
	}
	return false
}

type ClusterCreateRequest struct {
	Name              string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Provider          string           `protobuf:"bytes,2,opt,name=provider" json:"provider,omitempty"`
	Zone              string           `protobuf:"bytes,3,opt,name=zone" json:"zone,omitempty"`
	CredentialUID     string           `protobuf:"bytes,4,opt,name=credentialUID" json:"credentialUID,omitempty"`
	NodeGroups        []*InstanceGroup `protobuf:"bytes,5,rep,name=nodeGroups" json:"nodeGroups,omitempty"`
	KubernetesVersion string           `protobuf:"bytes,6,opt,name=kubernetesVersion" json:"kubernetesVersion,omitempty"`
	DoNotDelete       bool             `protobuf:"varint,7,opt,name=doNotDelete" json:"doNotDelete,omitempty"`
	// Default access level is to allow permission to the cluster
	// when no Role matched for that specif user or group. This can
	// set as
	//   - kubernetes:team-admin
	//   - kubernetes:cluster-admin
	//   - kubernetes:admin
	//   - kubernetes:editor
	//   - kubernetes:viewer
	//   - deny-access
	// If not set this will set ""
	DefaultAccessLevel string `protobuf:"bytes,8,opt,name=defaultAccessLevel" json:"defaultAccessLevel,omitempty"`
	GceProject         string `protobuf:"bytes,9,opt,name=gceProject" json:"gceProject,omitempty"`
}

func (m *ClusterCreateRequest) Reset()                    { *m = ClusterCreateRequest{} }
func (m *ClusterCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterCreateRequest) ProtoMessage()               {}
func (*ClusterCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ClusterCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterCreateRequest) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *ClusterCreateRequest) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *ClusterCreateRequest) GetCredentialUID() string {
	if m != nil {
		return m.CredentialUID
	}
	return ""
}

func (m *ClusterCreateRequest) GetNodeGroups() []*InstanceGroup {
	if m != nil {
		return m.NodeGroups
	}
	return nil
}

func (m *ClusterCreateRequest) GetKubernetesVersion() string {
	if m != nil {
		return m.KubernetesVersion
	}
	return ""
}

func (m *ClusterCreateRequest) GetDoNotDelete() bool {
	if m != nil {
		return m.DoNotDelete
	}
	return false
}

func (m *ClusterCreateRequest) GetDefaultAccessLevel() string {
	if m != nil {
		return m.DefaultAccessLevel
	}
	return ""
}

func (m *ClusterCreateRequest) GetGceProject() string {
	if m != nil {
		return m.GceProject
	}
	return ""
}

type ClusterDeleteRequest struct {
	Name                 string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ReleaseReservedIP    bool   `protobuf:"varint,2,opt,name=releaseReservedIP" json:"releaseReservedIP,omitempty"`
	Force                bool   `protobuf:"varint,3,opt,name=force" json:"force,omitempty"`
	KeepLodabalancers    bool   `protobuf:"varint,4,opt,name=keepLodabalancers" json:"keepLodabalancers,omitempty"`
	DeleteDynamicVolumes bool   `protobuf:"varint,5,opt,name=deleteDynamicVolumes" json:"deleteDynamicVolumes,omitempty"`
}

func (m *ClusterDeleteRequest) Reset()                    { *m = ClusterDeleteRequest{} }
func (m *ClusterDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterDeleteRequest) ProtoMessage()               {}
func (*ClusterDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ClusterDeleteRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterDeleteRequest) GetReleaseReservedIP() bool {
	if m != nil {
		return m.ReleaseReservedIP
	}
	return false
}

func (m *ClusterDeleteRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *ClusterDeleteRequest) GetKeepLodabalancers() bool {
	if m != nil {
		return m.KeepLodabalancers
	}
	return false
}

func (m *ClusterDeleteRequest) GetDeleteDynamicVolumes() bool {
	if m != nil {
		return m.DeleteDynamicVolumes
	}
	return false
}

type ClusterStartupConfigRequest struct {
	Uid             string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Role            string `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
	ResourceVersion int64  `protobuf:"varint,3,opt,name=resourceVersion" json:"resourceVersion,omitempty"`
}

func (m *ClusterStartupConfigRequest) Reset()                    { *m = ClusterStartupConfigRequest{} }
func (m *ClusterStartupConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterStartupConfigRequest) ProtoMessage()               {}
func (*ClusterStartupConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ClusterStartupConfigRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ClusterStartupConfigRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ClusterStartupConfigRequest) GetResourceVersion() int64 {
	if m != nil {
		return m.ResourceVersion
	}
	return 0
}

type ClusterStartupConfigResponse struct {
	Configuration string `protobuf:"bytes,1,opt,name=configuration" json:"configuration,omitempty"`
	Sku           string `protobuf:"bytes,2,opt,name=sku" json:"sku,omitempty"`
}

func (m *ClusterStartupConfigResponse) Reset()                    { *m = ClusterStartupConfigResponse{} }
func (m *ClusterStartupConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterStartupConfigResponse) ProtoMessage()               {}
func (*ClusterStartupConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ClusterStartupConfigResponse) GetConfiguration() string {
	if m != nil {
		return m.Configuration
	}
	return ""
}

func (m *ClusterStartupConfigResponse) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

type ClusterInstanceByIPRequest struct {
	Uid        string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	ExternalIP string `protobuf:"bytes,2,opt,name=externalIP" json:"externalIP,omitempty"`
}

func (m *ClusterInstanceByIPRequest) Reset()                    { *m = ClusterInstanceByIPRequest{} }
func (m *ClusterInstanceByIPRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstanceByIPRequest) ProtoMessage()               {}
func (*ClusterInstanceByIPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ClusterInstanceByIPRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ClusterInstanceByIPRequest) GetExternalIP() string {
	if m != nil {
		return m.ExternalIP
	}
	return ""
}

type ClusterInstanceByIPResponse struct {
	Instance *ClusterInstance `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
}

func (m *ClusterInstanceByIPResponse) Reset()                    { *m = ClusterInstanceByIPResponse{} }
func (m *ClusterInstanceByIPResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstanceByIPResponse) ProtoMessage()               {}
func (*ClusterInstanceByIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ClusterInstanceByIPResponse) GetInstance() *ClusterInstance {
	if m != nil {
		return m.Instance
	}
	return nil
}

type ClusterClientConfigRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ClusterClientConfigRequest) Reset()                    { *m = ClusterClientConfigRequest{} }
func (m *ClusterClientConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientConfigRequest) ProtoMessage()               {}
func (*ClusterClientConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ClusterClientConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ClusterClientConfigResponse struct {
	ClusterDomain   string `protobuf:"bytes,1,opt,name=clusterDomain" json:"clusterDomain,omitempty"`
	CaCert          string `protobuf:"bytes,2,opt,name=caCert" json:"caCert,omitempty"`
	ApiServerUrl    string `protobuf:"bytes,3,opt,name=apiServerUrl" json:"apiServerUrl,omitempty"`
	ClusterUserName string `protobuf:"bytes,4,opt,name=clusterUserName" json:"clusterUserName,omitempty"`
	UserCert        string `protobuf:"bytes,5,opt,name=userCert" json:"userCert,omitempty"`
	UserKey         string `protobuf:"bytes,6,opt,name=userKey" json:"userKey,omitempty"`
	ContextName     string `protobuf:"bytes,7,opt,name=contextName" json:"contextName,omitempty"`
	UserToken       string `protobuf:"bytes,8,opt,name=userToken" json:"userToken,omitempty"`
	Password        string `protobuf:"bytes,9,opt,name=password" json:"password,omitempty"`
}

func (m *ClusterClientConfigResponse) Reset()                    { *m = ClusterClientConfigResponse{} }
func (m *ClusterClientConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientConfigResponse) ProtoMessage()               {}
func (*ClusterClientConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ClusterClientConfigResponse) GetClusterDomain() string {
	if m != nil {
		return m.ClusterDomain
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetCaCert() string {
	if m != nil {
		return m.CaCert
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetApiServerUrl() string {
	if m != nil {
		return m.ApiServerUrl
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetClusterUserName() string {
	if m != nil {
		return m.ClusterUserName
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetUserCert() string {
	if m != nil {
		return m.UserCert
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetUserKey() string {
	if m != nil {
		return m.UserKey
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetContextName() string {
	if m != nil {
		return m.ContextName
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

func (m *ClusterClientConfigResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ClusterClientContainerRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DiskName string `protobuf:"bytes,2,opt,name=diskName" json:"diskName,omitempty"`
}

func (m *ClusterClientContainerRequest) Reset()                    { *m = ClusterClientContainerRequest{} }
func (m *ClusterClientContainerRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterClientContainerRequest) ProtoMessage()               {}
func (*ClusterClientContainerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ClusterClientContainerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterClientContainerRequest) GetDiskName() string {
	if m != nil {
		return m.DiskName
	}
	return ""
}

type ClusterInstance struct {
	Uid        string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	ExternalId string `protobuf:"bytes,2,opt,name=externalId" json:"externalId,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ExternalIP string `protobuf:"bytes,4,opt,name=externalIP" json:"externalIP,omitempty"`
	InternalIP string `protobuf:"bytes,5,opt,name=internalIP" json:"internalIP,omitempty"`
	Sku        string `protobuf:"bytes,6,opt,name=sku" json:"sku,omitempty"`
}

func (m *ClusterInstance) Reset()                    { *m = ClusterInstance{} }
func (m *ClusterInstance) String() string            { return proto.CompactTextString(m) }
func (*ClusterInstance) ProtoMessage()               {}
func (*ClusterInstance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ClusterInstance) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ClusterInstance) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *ClusterInstance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterInstance) GetExternalIP() string {
	if m != nil {
		return m.ExternalIP
	}
	return ""
}

func (m *ClusterInstance) GetInternalIP() string {
	if m != nil {
		return m.InternalIP
	}
	return ""
}

func (m *ClusterInstance) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

type ClusterUpdateRequest struct {
	Name        string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DoNotDelete bool             `protobuf:"varint,2,opt,name=doNotDelete" json:"doNotDelete,omitempty"`
	Settings    *ClusterSettings `protobuf:"bytes,3,opt,name=settings" json:"settings,omitempty"`
	// Default access level is to allow permission to the cluster
	// when no Role matched for that specif user or group. This can
	// set as
	//   - kubernetes:team-admin
	//   - kubernetes:cluster-admin
	//   - kubernetes:admin
	//   - kubernetes:editor
	//   - kubernetes:viewer
	//   - deny-access
	DefaultAccessLevel string `protobuf:"bytes,4,opt,name=defaultAccessLevel" json:"defaultAccessLevel,omitempty"`
}

func (m *ClusterUpdateRequest) Reset()                    { *m = ClusterUpdateRequest{} }
func (m *ClusterUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterUpdateRequest) ProtoMessage()               {}
func (*ClusterUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ClusterUpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterUpdateRequest) GetDoNotDelete() bool {
	if m != nil {
		return m.DoNotDelete
	}
	return false
}

func (m *ClusterUpdateRequest) GetSettings() *ClusterSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *ClusterUpdateRequest) GetDefaultAccessLevel() string {
	if m != nil {
		return m.DefaultAccessLevel
	}
	return ""
}

type ClusterReconfigureRequest struct {
	Name               string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ApplyToMaster      bool   `protobuf:"varint,2,opt,name=applyToMaster" json:"applyToMaster,omitempty"`
	Sku                string `protobuf:"bytes,3,opt,name=sku" json:"sku,omitempty"`
	Count              int64  `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	Version            string `protobuf:"bytes,5,opt,name=version" json:"version,omitempty"`
	SaltbaseVersion    string `protobuf:"bytes,6,opt,name=saltbaseVersion" json:"saltbaseVersion,omitempty"`
	KubeStarterVersion string `protobuf:"bytes,7,opt,name=kubeStarterVersion" json:"kubeStarterVersion,omitempty"`
	KubeletVersion     string `protobuf:"bytes,8,opt,name=kubeletVersion" json:"kubeletVersion,omitempty"`
	HostfactsVersion   string `protobuf:"bytes,9,opt,name=hostfactsVersion" json:"hostfactsVersion,omitempty"`
}

func (m *ClusterReconfigureRequest) Reset()                    { *m = ClusterReconfigureRequest{} }
func (m *ClusterReconfigureRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterReconfigureRequest) ProtoMessage()               {}
func (*ClusterReconfigureRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ClusterReconfigureRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClusterReconfigureRequest) GetApplyToMaster() bool {
	if m != nil {
		return m.ApplyToMaster
	}
	return false
}

func (m *ClusterReconfigureRequest) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *ClusterReconfigureRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ClusterReconfigureRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ClusterReconfigureRequest) GetSaltbaseVersion() string {
	if m != nil {
		return m.SaltbaseVersion
	}
	return ""
}

func (m *ClusterReconfigureRequest) GetKubeStarterVersion() string {
	if m != nil {
		return m.KubeStarterVersion
	}
	return ""
}

func (m *ClusterReconfigureRequest) GetKubeletVersion() string {
	if m != nil {
		return m.KubeletVersion
	}
	return ""
}

func (m *ClusterReconfigureRequest) GetHostfactsVersion() string {
	if m != nil {
		return m.HostfactsVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*ClusterSettings)(nil), "appscode.kubernetes.v1beta1.ClusterSettings")
	proto.RegisterType((*Cluster)(nil), "appscode.kubernetes.v1beta1.Cluster")
	proto.RegisterType((*ClusterDescribeRequest)(nil), "appscode.kubernetes.v1beta1.ClusterDescribeRequest")
	proto.RegisterType((*ClusterDescribeResponse)(nil), "appscode.kubernetes.v1beta1.ClusterDescribeResponse")
	proto.RegisterType((*ClusterDescribeResponse_ClusterSpec)(nil), "appscode.kubernetes.v1beta1.ClusterDescribeResponse.ClusterSpec")
	proto.RegisterType((*ClusterListRequest)(nil), "appscode.kubernetes.v1beta1.ClusterListRequest")
	proto.RegisterType((*ClusterListResponse)(nil), "appscode.kubernetes.v1beta1.ClusterListResponse")
	proto.RegisterType((*InstanceGroup)(nil), "appscode.kubernetes.v1beta1.InstanceGroup")
	proto.RegisterType((*ClusterCreateRequest)(nil), "appscode.kubernetes.v1beta1.ClusterCreateRequest")
	proto.RegisterType((*ClusterDeleteRequest)(nil), "appscode.kubernetes.v1beta1.ClusterDeleteRequest")
	proto.RegisterType((*ClusterStartupConfigRequest)(nil), "appscode.kubernetes.v1beta1.ClusterStartupConfigRequest")
	proto.RegisterType((*ClusterStartupConfigResponse)(nil), "appscode.kubernetes.v1beta1.ClusterStartupConfigResponse")
	proto.RegisterType((*ClusterInstanceByIPRequest)(nil), "appscode.kubernetes.v1beta1.ClusterInstanceByIPRequest")
	proto.RegisterType((*ClusterInstanceByIPResponse)(nil), "appscode.kubernetes.v1beta1.ClusterInstanceByIPResponse")
	proto.RegisterType((*ClusterClientConfigRequest)(nil), "appscode.kubernetes.v1beta1.ClusterClientConfigRequest")
	proto.RegisterType((*ClusterClientConfigResponse)(nil), "appscode.kubernetes.v1beta1.ClusterClientConfigResponse")
	proto.RegisterType((*ClusterClientContainerRequest)(nil), "appscode.kubernetes.v1beta1.ClusterClientContainerRequest")
	proto.RegisterType((*ClusterInstance)(nil), "appscode.kubernetes.v1beta1.ClusterInstance")
	proto.RegisterType((*ClusterUpdateRequest)(nil), "appscode.kubernetes.v1beta1.ClusterUpdateRequest")
	proto.RegisterType((*ClusterReconfigureRequest)(nil), "appscode.kubernetes.v1beta1.ClusterReconfigureRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Clusters service

type ClustersClient interface {
	List(ctx context.Context, in *ClusterListRequest, opts ...grpc.CallOption) (*ClusterListResponse, error)
	Describe(ctx context.Context, in *ClusterDescribeRequest, opts ...grpc.CallOption) (*ClusterDescribeResponse, error)
	Create(ctx context.Context, in *ClusterCreateRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error)
	Update(ctx context.Context, in *ClusterUpdateRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error)
	Reconfigure(ctx context.Context, in *ClusterReconfigureRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error)
	Delete(ctx context.Context, in *ClusterDeleteRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error)
	ClientConfig(ctx context.Context, in *ClusterClientConfigRequest, opts ...grpc.CallOption) (*ClusterClientConfigResponse, error)
	StartupConfig(ctx context.Context, in *ClusterStartupConfigRequest, opts ...grpc.CallOption) (*ClusterStartupConfigResponse, error)
	InstanceByIP(ctx context.Context, in *ClusterInstanceByIPRequest, opts ...grpc.CallOption) (*ClusterInstanceByIPResponse, error)
}

type clustersClient struct {
	cc *grpc.ClientConn
}

func NewClustersClient(cc *grpc.ClientConn) ClustersClient {
	return &clustersClient{cc}
}

func (c *clustersClient) List(ctx context.Context, in *ClusterListRequest, opts ...grpc.CallOption) (*ClusterListResponse, error) {
	out := new(ClusterListResponse)
	err := grpc.Invoke(ctx, "/appscode.kubernetes.v1beta1.Clusters/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Describe(ctx context.Context, in *ClusterDescribeRequest, opts ...grpc.CallOption) (*ClusterDescribeResponse, error) {
	out := new(ClusterDescribeResponse)
	err := grpc.Invoke(ctx, "/appscode.kubernetes.v1beta1.Clusters/Describe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Create(ctx context.Context, in *ClusterCreateRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error) {
	out := new(appscode_dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/appscode.kubernetes.v1beta1.Clusters/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Update(ctx context.Context, in *ClusterUpdateRequest, opts ...grpc.CallOption) (*appscode_dtypes.VoidResponse, error) {
	out := new(appscode_dtypes.VoidResponse)
	err := grpc.Invoke(ctx, "/appscode.kubernetes.v1beta1.Clusters/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Reconfigure(ctx context.Context, in *ClusterReconfigureRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error) {
	out := new(appscode_dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/appscode.kubernetes.v1beta1.Clusters/Reconfigure", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) Delete(ctx context.Context, in *ClusterDeleteRequest, opts ...grpc.CallOption) (*appscode_dtypes.LongRunningResponse, error) {
	out := new(appscode_dtypes.LongRunningResponse)
	err := grpc.Invoke(ctx, "/appscode.kubernetes.v1beta1.Clusters/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) ClientConfig(ctx context.Context, in *ClusterClientConfigRequest, opts ...grpc.CallOption) (*ClusterClientConfigResponse, error) {
	out := new(ClusterClientConfigResponse)
	err := grpc.Invoke(ctx, "/appscode.kubernetes.v1beta1.Clusters/ClientConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) StartupConfig(ctx context.Context, in *ClusterStartupConfigRequest, opts ...grpc.CallOption) (*ClusterStartupConfigResponse, error) {
	out := new(ClusterStartupConfigResponse)
	err := grpc.Invoke(ctx, "/appscode.kubernetes.v1beta1.Clusters/StartupConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clustersClient) InstanceByIP(ctx context.Context, in *ClusterInstanceByIPRequest, opts ...grpc.CallOption) (*ClusterInstanceByIPResponse, error) {
	out := new(ClusterInstanceByIPResponse)
	err := grpc.Invoke(ctx, "/appscode.kubernetes.v1beta1.Clusters/InstanceByIP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Clusters service

type ClustersServer interface {
	List(context.Context, *ClusterListRequest) (*ClusterListResponse, error)
	Describe(context.Context, *ClusterDescribeRequest) (*ClusterDescribeResponse, error)
	Create(context.Context, *ClusterCreateRequest) (*appscode_dtypes.LongRunningResponse, error)
	Update(context.Context, *ClusterUpdateRequest) (*appscode_dtypes.VoidResponse, error)
	Reconfigure(context.Context, *ClusterReconfigureRequest) (*appscode_dtypes.LongRunningResponse, error)
	Delete(context.Context, *ClusterDeleteRequest) (*appscode_dtypes.LongRunningResponse, error)
	ClientConfig(context.Context, *ClusterClientConfigRequest) (*ClusterClientConfigResponse, error)
	StartupConfig(context.Context, *ClusterStartupConfigRequest) (*ClusterStartupConfigResponse, error)
	InstanceByIP(context.Context, *ClusterInstanceByIPRequest) (*ClusterInstanceByIPResponse, error)
}

func RegisterClustersServer(s *grpc.Server, srv ClustersServer) {
	s.RegisterService(&_Clusters_serviceDesc, srv)
}

func _Clusters_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.kubernetes.v1beta1.Clusters/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).List(ctx, req.(*ClusterListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.kubernetes.v1beta1.Clusters/Describe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Describe(ctx, req.(*ClusterDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.kubernetes.v1beta1.Clusters/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Create(ctx, req.(*ClusterCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.kubernetes.v1beta1.Clusters/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Update(ctx, req.(*ClusterUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Reconfigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterReconfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Reconfigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.kubernetes.v1beta1.Clusters/Reconfigure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Reconfigure(ctx, req.(*ClusterReconfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.kubernetes.v1beta1.Clusters/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).Delete(ctx, req.(*ClusterDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_ClientConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterClientConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).ClientConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.kubernetes.v1beta1.Clusters/ClientConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).ClientConfig(ctx, req.(*ClusterClientConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_StartupConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterStartupConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).StartupConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.kubernetes.v1beta1.Clusters/StartupConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).StartupConfig(ctx, req.(*ClusterStartupConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clusters_InstanceByIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterInstanceByIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClustersServer).InstanceByIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appscode.kubernetes.v1beta1.Clusters/InstanceByIP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClustersServer).InstanceByIP(ctx, req.(*ClusterInstanceByIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Clusters_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appscode.kubernetes.v1beta1.Clusters",
	HandlerType: (*ClustersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Clusters_List_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _Clusters_Describe_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Clusters_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Clusters_Update_Handler,
		},
		{
			MethodName: "Reconfigure",
			Handler:    _Clusters_Reconfigure_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Clusters_Delete_Handler,
		},
		{
			MethodName: "ClientConfig",
			Handler:    _Clusters_ClientConfig_Handler,
		},
		{
			MethodName: "StartupConfig",
			Handler:    _Clusters_StartupConfig_Handler,
		},
		{
			MethodName: "InstanceByIP",
			Handler:    _Clusters_InstanceByIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1889 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x4f, 0x73, 0x1c, 0x47,
	0x15, 0xaf, 0xd9, 0x95, 0xb4, 0xab, 0x96, 0x65, 0xd9, 0x1d, 0xe1, 0x8c, 0xd7, 0x8e, 0x51, 0x0d,
	0x2e, 0x4a, 0xa5, 0xb2, 0xb5, 0x91, 0x12, 0x12, 0x13, 0x20, 0xe5, 0x68, 0x15, 0x12, 0x05, 0x45,
	0x11, 0x23, 0xdb, 0x54, 0x85, 0x03, 0xd5, 0x9a, 0x79, 0xda, 0x4c, 0x34, 0x9a, 0x1e, 0xba, 0x7b,
	0x84, 0x17, 0x97, 0x2f, 0xf9, 0x0a, 0x7c, 0x84, 0x14, 0x04, 0x6e, 0x1c, 0xe0, 0x02, 0x67, 0x28,
	0x2e, 0xa9, 0xa2, 0x8a, 0xe2, 0xc2, 0x09, 0xaa, 0x38, 0xf2, 0x21, 0xa8, 0xfe, 0x37, 0xd3, 0xb3,
	0xbb, 0xb2, 0x67, 0x0d, 0xb9, 0x6c, 0x4d, 0xbf, 0xee, 0xd7, 0xfd, 0xde, 0xeb, 0xf7, 0x7e, 0xef,
	0xd7, 0x8b, 0x96, 0xa3, 0xb4, 0xe0, 0x02, 0xd8, 0x66, 0xce, 0xa8, 0xa0, 0xf8, 0x06, 0xc9, 0x73,
	0x1e, 0xd1, 0x18, 0x36, 0x4f, 0x8b, 0x63, 0x60, 0x19, 0x08, 0xe0, 0x9b, 0xe7, 0x5b, 0xc7, 0x20,
	0xc8, 0x56, 0xef, 0xe6, 0x90, 0xd2, 0x61, 0x0a, 0x7d, 0x92, 0x27, 0x7d, 0x92, 0x65, 0x54, 0x10,
	0x91, 0xd0, 0x8c, 0x6b, 0xd5, 0xde, 0x2d, 0xab, 0x7a, 0xc1, 0xfc, 0xd7, 0x6b, 0xf3, 0xb1, 0x18,
	0xe5, 0xc0, 0xfb, 0xea, 0x57, 0x2f, 0x08, 0xbe, 0xf0, 0xd0, 0xca, 0x40, 0x5b, 0x73, 0x04, 0x42,
	0x24, 0xd9, 0x90, 0xe3, 0x6f, 0xa2, 0xcb, 0x29, 0x1d, 0xee, 0x65, 0x31, 0x3c, 0x3e, 0x64, 0x70,
	0x92, 0x3c, 0xf6, 0xbd, 0x35, 0x6f, 0x7d, 0x31, 0x1c, 0x93, 0xe2, 0x4d, 0x84, 0x53, 0x3a, 0x3c,
	0x12, 0x94, 0x91, 0x21, 0xec, 0x27, 0x27, 0x20, 0x92, 0x33, 0xf0, 0x5b, 0x6b, 0xde, 0x7a, 0x3b,
	0x9c, 0x32, 0x83, 0xbf, 0x8b, 0xae, 0x9f, 0xd1, 0x2c, 0x11, 0x94, 0x25, 0xd9, 0x84, 0x5a, 0x5b,
	0xa9, 0x5d, 0xbc, 0x20, 0xf8, 0x67, 0x07, 0x75, 0x8c, 0xa5, 0xf8, 0x0a, 0x6a, 0x17, 0x49, 0x6c,
	0xcc, 0x92, 0x9f, 0x18, 0xa3, 0xb9, 0x8c, 0x98, 0xd3, 0x17, 0x43, 0xf5, 0x8d, 0x7b, 0xa8, 0x9b,
	0x33, 0x7a, 0x9e, 0xc4, 0xc0, 0xd4, 0xf6, 0x8b, 0x61, 0x39, 0xc6, 0x97, 0x51, 0x8b, 0x72, 0x7f,
	0x4e, 0x49, 0x5b, 0x94, 0xe3, 0x6b, 0x68, 0x81, 0xc1, 0x30, 0xa1, 0x99, 0x3f, 0xaf, 0x64, 0x66,
	0x24, 0xf7, 0xfd, 0x39, 0xcd, 0xc0, 0x5f, 0xd0, 0xfb, 0xca, 0x6f, 0x7c, 0x13, 0x2d, 0x46, 0x0c,
	0x88, 0x80, 0xf8, 0x1d, 0xe1, 0x77, 0x94, 0xdd, 0x95, 0x00, 0xbf, 0x8b, 0xe6, 0xd3, 0x24, 0x3b,
	0xe5, 0x7e, 0x77, 0xad, 0xbd, 0xbe, 0xb4, 0xdd, 0xdf, 0x7c, 0xc6, 0xed, 0x6e, 0x1a, 0x87, 0x36,
	0xf7, 0xa5, 0xc6, 0xbb, 0x99, 0x60, 0xa3, 0x50, 0x6b, 0xe3, 0x35, 0xb4, 0x14, 0xd3, 0x03, 0x2a,
	0x76, 0x21, 0x05, 0x01, 0xfe, 0xe2, 0x9a, 0xb7, 0xde, 0x0d, 0x5d, 0x91, 0x34, 0x99, 0x0b, 0x22,
	0x0a, 0xee, 0x23, 0x6d, 0xb2, 0x1e, 0x49, 0x4d, 0xfd, 0x35, 0x20, 0x05, 0x07, 0x7f, 0x49, 0x4d,
	0xba, 0x22, 0x7c, 0x0b, 0xa1, 0x61, 0x04, 0x87, 0x8c, 0x7e, 0x0a, 0x91, 0xf0, 0x2f, 0xa9, 0x05,
	0x8e, 0x44, 0x26, 0x80, 0xb4, 0x35, 0x05, 0xf1, 0x08, 0x18, 0x97, 0x41, 0x59, 0xd6, 0x09, 0x50,
	0x97, 0xe2, 0x75, 0xb4, 0xc2, 0x49, 0x2a, 0x8e, 0x09, 0x07, 0xbb, 0xf0, 0xb2, 0x5a, 0x38, 0x2e,
	0x96, 0xa9, 0x22, 0x75, 0x8f, 0x04, 0x61, 0x02, 0x98, 0x5d, 0xbc, 0xa2, 0x16, 0x4f, 0x99, 0x91,
	0x21, 0xce, 0x68, 0x0c, 0x03, 0x5a, 0x64, 0xc2, 0xbf, 0xb2, 0xe6, 0xad, 0xcf, 0x87, 0x95, 0x00,
	0x07, 0xe8, 0x12, 0xc9, 0x93, 0x23, 0x60, 0xe7, 0xc0, 0x1e, 0xb2, 0xd4, 0xbf, 0xaa, 0xf6, 0xa9,
	0xc9, 0xe4, 0xe5, 0xcb, 0x7d, 0x1f, 0x72, 0x60, 0x3e, 0xd6, 0x97, 0x6f, 0xc7, 0x52, 0x5f, 0x7e,
	0x1f, 0x12, 0xce, 0x7f, 0x46, 0x59, 0xec, 0xbf, 0xa4, 0xf5, 0x5d, 0x99, 0x8c, 0x6e, 0x44, 0x06,
	0xc0, 0x84, 0xbf, 0xaa, 0xa3, 0xab, 0x47, 0xd2, 0x67, 0xb9, 0x6e, 0x07, 0x08, 0x03, 0xf6, 0x80,
	0x9e, 0x42, 0xe6, 0x7f, 0x4d, 0xfb, 0x3c, 0x26, 0xc6, 0xef, 0xa3, 0x2e, 0x37, 0x25, 0xe5, 0x5f,
	0x5b, 0xf3, 0xd6, 0x97, 0xb6, 0xef, 0x34, 0xc9, 0x05, 0x5b, 0x86, 0x61, 0xa9, 0x8d, 0xb7, 0xd1,
	0x6a, 0x92, 0x71, 0x41, 0xb2, 0x08, 0x42, 0x4a, 0x45, 0x69, 0xf7, 0xcb, 0xea, 0xe0, 0xa9, 0x73,
	0xd8, 0x47, 0x9d, 0x73, 0x13, 0x66, 0x5f, 0x2d, 0xb3, 0x43, 0x59, 0x3c, 0xfc, 0xb4, 0xf0, 0xaf,
	0xeb, 0xe2, 0xe1, 0xa7, 0x85, 0x93, 0xd0, 0x3b, 0x23, 0xbf, 0xa7, 0xe4, 0x95, 0x40, 0xde, 0x5d,
	0x0c, 0x27, 0xa4, 0x48, 0xc5, 0x3b, 0x51, 0x04, 0x9c, 0xef, 0xc3, 0x39, 0xa4, 0xfe, 0x0d, 0x7d,
	0x77, 0x93, 0x33, 0xbd, 0x7b, 0x08, 0x55, 0xe9, 0x2c, 0x4f, 0x3b, 0x85, 0x91, 0x2d, 0xd5, 0x53,
	0x18, 0xe1, 0x55, 0x34, 0x7f, 0x4e, 0xd2, 0xc2, 0xd6, 0xaa, 0x1e, 0xbc, 0xd5, 0xba, 0xe7, 0x05,
	0x1b, 0xe8, 0x9a, 0x09, 0xc2, 0x2e, 0xf0, 0x88, 0x25, 0xc7, 0x10, 0xc2, 0x4f, 0x0b, 0xe0, 0x62,
	0xb2, 0xe0, 0x83, 0x5f, 0xb6, 0xd1, 0xcb, 0x13, 0x8b, 0x79, 0x4e, 0x33, 0x0e, 0xf8, 0x6d, 0xd4,
	0x31, 0x08, 0xab, 0x34, 0x96, 0xb6, 0x6f, 0x37, 0x09, 0x7c, 0x68, 0x95, 0xf0, 0x03, 0x34, 0xc7,
	0x73, 0x88, 0x94, 0x81, 0x4b, 0xdb, 0xf7, 0x9b, 0x28, 0x8f, 0xdb, 0x50, 0xde, 0x66, 0x0e, 0x51,
	0xa8, 0x76, 0xc3, 0xb7, 0xd1, 0x32, 0xcd, 0x81, 0x29, 0x7c, 0x3e, 0xfc, 0x24, 0x89, 0x0d, 0x26,
	0xd5, 0x85, 0xbd, 0x2f, 0x3d, 0xb4, 0xe4, 0xe8, 0xca, 0x5a, 0x8c, 0x68, 0x26, 0x48, 0x92, 0x01,
	0xd3, 0xe5, 0xe0, 0xa9, 0x72, 0x18, 0x93, 0x2a, 0xb0, 0xa3, 0xb1, 0x5e, 0xd1, 0x52, 0x2b, 0xca,
	0xb1, 0xcc, 0x77, 0x0e, 0xec, 0x3c, 0x89, 0x4c, 0x41, 0xb5, 0xd5, 0x7c, 0x4d, 0x26, 0xf3, 0x85,
	0x45, 0x7a, 0x7a, 0x4e, 0x4d, 0xdb, 0xa1, 0xdc, 0x59, 0x50, 0x41, 0xd2, 0x41, 0x5e, 0x28, 0x70,
	0x6c, 0x87, 0xe5, 0x58, 0x62, 0x8d, 0xfa, 0xfe, 0x10, 0xce, 0x28, 0x1b, 0x29, 0x94, 0x6c, 0x87,
	0xae, 0x28, 0xb8, 0x83, 0xb0, 0x71, 0x67, 0x3f, 0xe1, 0xc2, 0xde, 0x67, 0x85, 0x5d, 0xde, 0x5a,
	0xbb, 0xc2, 0xae, 0xe0, 0x47, 0xe8, 0xa5, 0xda, 0x6a, 0x73, 0xa1, 0xf7, 0x51, 0xd7, 0xdc, 0x8d,
	0x56, 0x68, 0x7a, 0xa3, 0xa5, 0x56, 0x10, 0xa1, 0xe5, 0x3d, 0x53, 0x26, 0xef, 0x31, 0x5a, 0xe4,
	0xb6, 0x0a, 0xbc, 0xaa, 0x0a, 0x56, 0xd1, 0x7c, 0x54, 0x86, 0xaf, 0x1d, 0xea, 0x01, 0xde, 0x40,
	0x57, 0x0a, 0x0e, 0x47, 0x39, 0x15, 0x56, 0x9f, 0xab, 0xf8, 0x75, 0xc3, 0x09, 0x79, 0xf0, 0x9f,
	0x16, 0x5a, 0x35, 0x47, 0x0f, 0x54, 0xf9, 0x58, 0x77, 0x6d, 0x77, 0xf2, 0x2e, 0xe8, 0x4e, 0xad,
	0xb1, 0xee, 0x64, 0xbb, 0x4e, 0xdb, 0xe9, 0x3a, 0xb7, 0xd1, 0x72, 0xc4, 0x20, 0x86, 0x4c, 0x24,
	0x24, 0x7d, 0xb8, 0xb7, 0x6b, 0x9a, 0x57, 0x5d, 0x88, 0x3f, 0x40, 0x48, 0xe2, 0xa4, 0xf2, 0x91,
	0xfb, 0xf3, 0x2a, 0x56, 0x1b, 0xcf, 0x8c, 0x55, 0x2d, 0x2c, 0xa1, 0xa3, 0x8d, 0xef, 0xa0, 0xab,
	0xd5, 0x7a, 0x8b, 0xd9, 0xba, 0x11, 0x4e, 0x4e, 0x8c, 0x37, 0xac, 0xce, 0x64, 0xc3, 0x9a, 0x0e,
	0x24, 0xdd, 0x8b, 0x80, 0x64, 0xac, 0x4d, 0x2d, 0x8e, 0xb7, 0xa9, 0xe0, 0xaf, 0x5e, 0x19, 0x6e,
	0x7d, 0xc2, 0xb3, 0xc2, 0x7d, 0x07, 0x5d, 0x65, 0x90, 0x02, 0xe1, 0xb2, 0x44, 0x65, 0x97, 0x88,
	0xf7, 0x0e, 0x55, 0xdc, 0xbb, 0xe1, 0xe4, 0x84, 0xcc, 0x85, 0x13, 0xca, 0x22, 0x30, 0x57, 0xad,
	0x07, 0x2a, 0x20, 0x00, 0xf9, 0x3e, 0x8d, 0xc9, 0x31, 0x49, 0x65, 0xd0, 0x98, 0xe6, 0x10, 0xdd,
	0x70, 0x72, 0x42, 0xa2, 0x76, 0xac, 0xcc, 0xda, 0x1d, 0x65, 0xe4, 0x2c, 0x89, 0x1e, 0xd1, 0xb4,
	0x38, 0x03, 0xae, 0x6a, 0xa8, 0x1b, 0x4e, 0x9d, 0x0b, 0xce, 0xd0, 0x0d, 0x5b, 0xfc, 0xb2, 0x21,
	0x16, 0xf9, 0x80, 0x66, 0x27, 0xc9, 0xf0, 0x42, 0x18, 0x94, 0xae, 0x32, 0x9a, 0x96, 0xbc, 0x47,
	0x7e, 0xcb, 0x16, 0xc5, 0x80, 0xd3, 0x82, 0x45, 0x65, 0x5b, 0xd6, 0xec, 0x6a, 0x5c, 0x1c, 0x3c,
	0x42, 0x37, 0xa7, 0x1f, 0x67, 0xea, 0x4e, 0xe6, 0x9c, 0x92, 0x14, 0x1a, 0xa1, 0xcc, 0xc9, 0x75,
	0xa1, 0x2d, 0xa5, 0x56, 0x59, 0x4a, 0xc1, 0x01, 0xea, 0x99, 0x7d, 0x6d, 0x76, 0xed, 0x8c, 0xf6,
	0x0e, 0x2f, 0xf6, 0xe2, 0x16, 0x42, 0xf0, 0x58, 0x00, 0xcb, 0x48, 0x6a, 0x6e, 0x65, 0x31, 0x74,
	0x24, 0xc1, 0xb0, 0x0c, 0x4b, 0x7d, 0x3f, 0x63, 0xe6, 0xfb, 0xa8, 0x6b, 0x7b, 0xa0, 0x01, 0xfc,
	0x46, 0x9d, 0xd6, 0xee, 0x15, 0x96, 0xda, 0xc1, 0xab, 0xa5, 0xe1, 0x83, 0x34, 0x81, 0x4c, 0xd4,
	0xc3, 0x3f, 0x25, 0xaf, 0x82, 0x3f, 0xb6, 0x4a, 0xdb, 0xea, 0x2a, 0x4e, 0x08, 0x4d, 0x8e, 0xd2,
	0x33, 0x92, 0x54, 0x21, 0x74, 0x85, 0x0e, 0xdb, 0x68, 0xd5, 0xd8, 0xc6, 0x38, 0xd3, 0x69, 0x4f,
	0x61, 0x3a, 0xeb, 0x68, 0xc5, 0x6c, 0x26, 0xc9, 0xcd, 0x81, 0x34, 0x50, 0x43, 0xc3, 0xb8, 0x58,
	0x42, 0x4e, 0xc1, 0x81, 0xa9, 0x73, 0x34, 0xcd, 0x2d, 0xc7, 0x12, 0xff, 0xe5, 0xf7, 0x0f, 0x60,
	0x64, 0x4a, 0xdc, 0x0e, 0x65, 0x61, 0xcb, 0x5e, 0x03, 0x8f, 0x85, 0xda, 0xbb, 0xa3, 0xf9, 0xa4,
	0x23, 0x92, 0xfc, 0x41, 0x2e, 0xd6, 0x6c, 0x48, 0xd7, 0x73, 0x25, 0x50, 0x40, 0x67, 0x19, 0xcb,
	0xa2, 0x01, 0x3a, 0x33, 0x0e, 0x3e, 0x42, 0xaf, 0x8c, 0x07, 0x4f, 0x37, 0xb5, 0xe7, 0x20, 0x67,
	0x9c, 0xf0, 0xd3, 0x83, 0x8a, 0xef, 0x97, 0xe3, 0xe0, 0x37, 0xd5, 0x7b, 0xc6, 0x5e, 0xef, 0x73,
	0xf2, 0x2d, 0x9e, 0xc8, 0xb7, 0xea, 0x35, 0xd1, 0x76, 0x4e, 0xad, 0xe7, 0xe8, 0xdc, 0x78, 0x8e,
	0xca, 0xf9, 0x24, 0x2b, 0xe7, 0x75, 0x78, 0x1d, 0x89, 0xad, 0x92, 0x85, 0xaa, 0x4a, 0xfe, 0x5c,
	0xe1, 0xd7, 0xc3, 0x3c, 0x7e, 0x4e, 0xbb, 0x18, 0x83, 0xd7, 0xd6, 0x24, 0xbc, 0xba, 0x7c, 0xb3,
	0xfd, 0x3f, 0xf1, 0xcd, 0xe9, 0x40, 0x3d, 0x77, 0x11, 0x50, 0x07, 0x7f, 0x6a, 0xa1, 0xeb, 0xb6,
	0xe5, 0x82, 0xc5, 0x86, 0x67, 0x7a, 0x73, 0x1b, 0x2d, 0x93, 0x3c, 0x4f, 0x47, 0x0f, 0xe8, 0x87,
	0x44, 0xf1, 0x34, 0xed, 0x4f, 0x5d, 0x68, 0x43, 0xd6, 0x9e, 0xd2, 0xa3, 0xe7, 0xdc, 0x1e, 0xed,
	0x70, 0xdd, 0xf9, 0x3a, 0xd7, 0x9d, 0xf2, 0x42, 0x59, 0x98, 0xe5, 0x85, 0xd2, 0xb9, 0xf0, 0x85,
	0x32, 0xf9, 0x46, 0xea, 0x4e, 0x7d, 0x23, 0x6d, 0xa0, 0x2b, 0x9f, 0x50, 0x2e, 0x4e, 0x48, 0x24,
	0xca, 0x1e, 0xaa, 0xab, 0x60, 0x42, 0xbe, 0xfd, 0xab, 0x15, 0xd4, 0x35, 0x71, 0xe4, 0xf8, 0xd7,
	0x1e, 0x9a, 0x93, 0x24, 0x08, 0x37, 0x7a, 0x41, 0x3a, 0xe4, 0xaa, 0xf7, 0x6a, 0x73, 0x05, 0x0d,
	0x52, 0xc1, 0xf7, 0x3e, 0xfb, 0xbd, 0xdf, 0xea, 0x7a, 0x9f, 0xfd, 0xed, 0xdf, 0xbf, 0x68, 0x6d,
	0xe1, 0x7e, 0xff, 0x27, 0xb5, 0xbf, 0x0d, 0xaa, 0x4d, 0xfa, 0x66, 0x93, 0xbe, 0xe5, 0x55, 0xfd,
	0x4f, 0x39, 0xcd, 0xf0, 0x1f, 0x3c, 0xd4, 0xb5, 0x04, 0x18, 0xbf, 0x36, 0x1b, 0x5d, 0xd6, 0x26,
	0xbf, 0xfe, 0x22, 0x1c, 0x3b, 0x18, 0x38, 0x66, 0xbf, 0x89, 0xbf, 0x35, 0x83, 0xd9, 0x4f, 0x8a,
	0x24, 0x7e, 0xaa, 0x8d, 0xff, 0xdc, 0x43, 0x0b, 0x9a, 0xad, 0xe1, 0xad, 0x26, 0x56, 0xd4, 0x98,
	0x5d, 0xcf, 0xe1, 0xa1, 0xfa, 0xdf, 0x95, 0xcd, 0x7d, 0x9a, 0x0d, 0xc3, 0x22, 0xcb, 0x92, 0xac,
	0x6c, 0x02, 0xc1, 0x7d, 0xc7, 0xd0, 0xd7, 0x83, 0x59, 0xe3, 0xfb, 0x96, 0xb7, 0xa1, 0xac, 0xd4,
	0x20, 0xd1, 0xcc, 0xca, 0x1a, 0xa0, 0xf4, 0x5e, 0x99, 0xb0, 0xf2, 0x11, 0x4d, 0xe2, 0xd2, 0xbc,
	0xf7, 0x1c, 0xf3, 0xbe, 0xd3, 0x7b, 0x63, 0x96, 0x38, 0xca, 0x6a, 0x7e, 0x5a, 0x5a, 0xf9, 0x17,
	0x0f, 0x2d, 0x39, 0x08, 0x80, 0xdf, 0x68, 0xc4, 0xd2, 0x27, 0x20, 0xa3, 0x61, 0x54, 0x7f, 0xec,
	0x98, 0xfd, 0x51, 0xef, 0x83, 0xd9, 0xcd, 0x26, 0x91, 0xfa, 0xaf, 0xac, 0xcf, 0x2a, 0x0b, 0x4a,
	0x57, 0xbe, 0xf0, 0xd0, 0x82, 0x01, 0xd6, 0xad, 0x66, 0xc9, 0xe9, 0x30, 0xd0, 0x86, 0x0e, 0xec,
	0x3a, 0x0e, 0xdc, 0xdb, 0x78, 0xc1, 0xb8, 0xe3, 0xbf, 0x7b, 0xe8, 0x92, 0x4b, 0x3d, 0xf0, 0x9b,
	0x8d, 0xd2, 0x78, 0x92, 0xdf, 0xf4, 0xee, 0xcd, 0xae, 0x68, 0x3c, 0x09, 0x1d, 0x4f, 0xbe, 0x8f,
	0x77, 0x67, 0xf7, 0x24, 0x52, 0xbb, 0xde, 0xd5, 0xf7, 0xa0, 0xfd, 0xfa, 0x57, 0x0b, 0x2d, 0xd7,
	0x68, 0x29, 0x6e, 0x64, 0xdf, 0x34, 0xe2, 0xdc, 0xfb, 0xf6, 0x0b, 0x68, 0x1a, 0xd7, 0xfe, 0xe1,
	0x39, 0xbe, 0x7d, 0xe9, 0xe1, 0x93, 0x99, 0x61, 0x86, 0xeb, 0x7d, 0xad, 0x73, 0x4f, 0x24, 0x49,
	0x7f, 0xda, 0x37, 0x2d, 0x8a, 0xf7, 0x9f, 0x8c, 0xb1, 0x72, 0x7d, 0xad, 0x1f, 0x47, 0x98, 0x7c,
	0xe5, 0x27, 0xe1, 0xdf, 0xb5, 0xd0, 0x25, 0x97, 0x52, 0x37, 0xcb, 0x9d, 0x29, 0xa4, 0xbe, 0x59,
	0xee, 0x4c, 0x63, 0xef, 0xc1, 0x6f, 0xdd, 0x00, 0x7f, 0xee, 0xe1, 0x1f, 0xce, 0xec, 0xb6, 0xa5,
	0xef, 0x77, 0x8f, 0x47, 0x77, 0x93, 0xbc, 0xff, 0xa4, 0x62, 0x65, 0x26, 0x96, 0x07, 0x78, 0xff,
	0xff, 0xb9, 0xe9, 0xce, 0xdb, 0xe8, 0x1b, 0x11, 0x3d, 0xab, 0x3c, 0x26, 0x79, 0x32, 0xc5, 0xeb,
	0x9d, 0x4b, 0xc6, 0xed, 0x43, 0x46, 0x05, 0x3d, 0xf4, 0x3e, 0xee, 0x98, 0x89, 0xe3, 0x05, 0xf5,
	0xe7, 0xfb, 0x6b, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x90, 0x2f, 0x96, 0x09, 0x18, 0x00,
	0x00,
}
